### ISSUE TITLE
(com.aws.greengrass.Nucleus): Reduce volume of INFO level logging

### ISSUE THREAD

**Issue by japsu** [aws-greengrass/aws-greengrass-nucleus#1002]
**Feature Description**
Thousands of log lines are written into the `greengrass.log` log file for even relatively simple operations such as deployments. The logging volume should be reduced to increase usability of the logs and reduce wear on embedded storage.

**Use Case**
Embedded solutions may often run on devices which not only are storage-constrained, but the storage may also have limited write cycles or poor wear leveling, such as is the case for inexpensive eMMC storage.

While logs are important for monitoring the status of the device and especially crucial for troubleshooting, and log rotation reduces the logs stored to a manageable amount, a large volume of logging will wear down embedded device storage faster.

**Proposed Solution**
Move all current INFO level logging to the DEBUG log level and only hand-pick the most useful log messages back to INFO.

**Other**

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi Santtu,
Another thing you can consider is to update the log level which is used by Greengrass. You can configure it to log any level of logs, so you should configure it to only log WARN and ERROR logs.

**Comment by japsu** [comment]
That is beside the point.

Nearly everything is logged at the INFO level. If I were to raise the bar to WARN, I would lose most useful log input, such as "deployment started" and "deployment successfully finished".

The problem is that there are thousands of lines of redundant logging that conveys very little information in between. Most of this logging is internal and technical in nature and would belong on the DEBUG log level.

**Comment by MikeDombo** [comment]
If there are specific logs which you don't think should be at info level, can you please point them out? We're also very happy to accept pull requests if you want to do that as well.

**Comment by japsu** [comment]
When I install a GGv2 device from scratch and deploy a deployment that has ten or so components, afterwards the greengrass.log log file contains roughly 1500 lines. 

For me the most useful ones are

- nucleus started (x1)
- new deployment job received (x1)
- deployment job started (x1)
- deployment of a component started (x10)
- deployment of a component finished (x10)
- deployment job finished (x1)

That would be 24 lines. Everything else related to the deployment process is only noise.

**Comment by MikeDombo** [comment]
Understood, thank you. We'll audit our logging at info level to make sure the logs are as relevant as possible.
