### ISSUE TITLE
(com.aws.greengrass.easysetup): IoT Thing Policy Option

### ISSUE THREAD

**Issue by mora0136** [aws-greengrass/aws-greengrass-nucleus#1015]
**Feature Description**
When installing with --provision, a policy name specifiying the IoT policy to attach to the IoT Thing Certs can be supplied as an argument. If the policy exists, then attach it to the certs, otherwise create the policy using a default policy document. In the absence of the argument, the existing behaviour of using the GreengrassV2IoTThingPolicy should be used.

**Use Case**
When trying to apply minimal policy definitions, different core devices have different permissions that they should have access to. By specifying the desired policy document at provision, it saves effort swapping policies after the provision process.

**Proposed Solution**
Move the static GG_THING_POLICY_NAME in DeviceProvisioningHelper.java to GreengrassSetup.java as an argument passed with --thing-policy. The behaviour would be the same as --tes-role-name where it will default to GreengrassV2IoTThingPolicy with a generic policy.

**Other**

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Closed by #1016
