### ISSUE TITLE
(logging): cutting log entries short makes some uninformative

### ISSUE THREAD

**Issue by plafer** [aws-greengrass/aws-greengrass-nucleus#1030]
**Feature Description**
Log entries are cut short when too long, which can make them useless. For example,

2021-07-23T12:53:14.376Z [WARN] (pool-2-thread-20) com.example.HelloWorld: shell-runner-error. {scriptName=services.com.example.HelloWorld.lifecycle.Install.Script, serviceName=com.example.HelloWorld, currentState=NEW, command=["bash -c '/usr/local/greengrass/v2/packages/artifacts/com.example.HelloWorld/0.0..."]}

**Use Case**
I currently can't use the logs at all because the important information has been cut off.

**Proposed Solution**
There could be a `trim logs` flag in the Nucleus which controls whether or not the user wants the logs trimmed.

**Comment by MikeDombo** [comment]
Hi, we do not trim almost any logs other than what you pointed out.

Why is it helpful for you to see the whole thing? 

If you want to see the command after having the configuration interpolated, you could add the command echo to the front and then the whole command line would be printed to the log as standard output.

**Comment by plafer** [comment]
The ultimate goal is to get more information than "Installation failed", and I wasn't sure what came after the dots.

As an alternative, would it be possible to forward any output from the failing command within the install script? Otherwise, I need to add prints everywhere to figure out which part of the install script is failing, redeploy, and after a couple of iterations, finally get to the error message (which is what I ended up doing). It would be great to already have it in the logs.

**Comment by MikeDombo** [comment]
All standard output and standard error is logged exactly as-is from the component, no trimming of any sort.

What comes after the `...` is just the rest of the command which is not likely to be useful.

**Comment by plafer** [comment]
Interesting, I'm not quite sure what happened there then. I'll close the issue, and if ever I reecounter something similar, I'll reopen with more details.

Thanks for the help!
