### ISSUE TITLE
(com.aws.greengrass.Nucleus): generate a json deployment from an existing deployment 

### ISSUE THREAD

**Issue by emaayan** [aws-greengrass/aws-greengrass-nucleus#1039]
**Feature Description**

have the ability  to export a current deployment in the web ui to a json file 

**Use Case**
it can provide a much better learning curve then having to write one by hand from scratch, plus a deployment can be re-used a lot faster this way 

**Proposed Solution**
on the overview of a deployment there would a button called "export deployment" that download a json file to the user's machine. 
a similar functionality can be found on the lambda dashboard  where you click "Actions" and then export function and finally download sam file

**Comment by MikeDombo** [comment]
I have passed this request on to the console team. Since console is not open source I will be closing this issue here.
