### ISSUE TITLE
(Nucleus): Expand compressed artifacts into `{artifacts:path}` instead of `{artifacts:decompressedPath}`

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-nucleus#1047]
**Feature Description**
Uncompressed versions of the artifacts should be found in `{artifacts:path}`, while compressed archives should be in `{artifacts:compressedPath}`.

**Use Case**
Local development flow via `greengrass-cli` only support uncompressed component artifacts, but these are typically compressed when uploaded to cloud. 
This means that the recipe used locally and the one used to upload the cloud component differs: the local recipe refers to artifacts via `{artifacts:path}` while the cloud one needs to use `{artifacts:decompressedPath}/<archivename>` while in `{artifacts:path}` one finds the compressed archive.

This **introduces additional friction to the development process** and also means that test performed on local components are not representative, as the recipe lifecycle scripts for the cloud component differ.

**Proposed Solution**
Compressed artifacts should be stored in `{artifacts:compressedPath}` which are uncompressed into `{artifacts:path}`, without creating a sub-folder with the archive name. 

It should be reasonable to expect that if the component recipe contains multiple compressed artifacts containing the same paths, the behaviour will not be deterministic (ie the last uncompressed artifact wins). 

If a deterministic behaviour is required the user must ensure that the archives do not contain files with same path (eg by adding a unique root folder to the archive).

**Other**
This is a breaking change for existing recipes, and should be solved by creating a new recipe format version.
It does not have an impact on Greengrass Core software which can run components with recipes written with both versions.

* [ ] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Greengrass local CLI does not only support uncompressed artifacts. Compressed artifacts are supported in the same way that they are supported when uploaded to the cloud. If you provide a ZIP in the artifacts and tell Greengrass to unarchive it, then it will indeed be unarchived during the local deployment.

**Comment by massi-ang** [comment]
Thanks for providing the information on how to emulate the unpacking behaviour for local deployments. It does add an additional archiving step to my local development workflow, though, but it can be scripted.
