### ISSUE TITLE
(greengrass): Cannot delete deployment

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1050]
**Describe the bug**
Cannot delete deployment

**To Reproduce**
1. Install greengrass on a device and give it a thing-name `burro-7771`.
2. Create a thing group `test-7771` and add the device `burro-7771` into it.
3. Create a group deployment `Deployment for 7771 - 2.7.0` with a random component and deploy it to the group `test-7771`.
4. After the group deployment in `Active` status and the deployment to `burro-7771` is successful. 
5. Create a group deployment `Deployment for 7771 - 2.7.0` with *no component* and deploy it to the group `test-7771`.
6. After the group deployment in `Active` status and the deployment to `burro-7771` is successful.
7. Delete the group `test-7771`.
8. Cancel the group deployment `Deployment for 7771 - 2.7.0`
9. Try to delete the deployment since it's empty already but don't know how to delete the deployment. 

**Expected behavior**
Expecting that the deployment can be deleted since it's empty already. ( Or even if it's not empty, just try to make it cleaner on the web UI.  But wouldn't it be harder to keep track of anything be deployed? )
Or, is there a way to hide those empty deployments from the UI part?

Empty deployment example:
![Screenshot from 2021-08-10 11-05-40](https://user-images.githubusercontent.com/82956718/128901340-677aaf06-8832-48e4-adcc-4cd0b92ee08c.png)

Several empty deployments under a core device which should be wipe out.
![Screenshot from 2021-08-10 12-55-08](https://user-images.githubusercontent.com/82956718/128901822-6cd316cc-5316-4b3f-a8c4-ef8d6f76fc08.png)

**Actual behavior**
Cannot delete the (empty) deployments. 

**Environment**
 - OS: Ubuntu 18.04
 - JDK version: JAVA8
 - Nucleus version: 2.3.0

**Additional context**
Impact of the setting : It may makes people hard to manage stuff since it's messy at some point.

**Comment by MikeDombo** [comment]
Hi Debo,
Sorry but deployments are not able to be deleted at this time. This is not a bug, it is intended. We are working to add a delete deployment API, but it does not yet exist.
