### ISSUE TITLE
(greengrass): cannot remove core device from a deleted thinggroup

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1051]
**Describe the bug**
Cannot remove core device from a deleted thinggroup

**To Reproduce**
1. Install greengrass on a device and give it a thing-name `burro-7771`.
2. Create a thing group `test-7771` and add the device `burro-7771` into it.
3. Create a group deployment `Deployment for 7771 - 2.7.0` with a random component and deploy it to the group `test-7771`.
4. After the group deployment in `Active` status and the deployment to `burro-7771` is successful. 
5. Create a group deployment `Deployment for 7771 - 2.7.0` with *no component* and deploy it to the group `test-7771`.
6. After the group deployment in `Active` status and the deployment to `burro-7771` is successful.
7. Delete the group `test-7771`.
8. Cancel the group deployment `Deployment for 7771 - 2.7.0`
9. Try to remove the core device `burro-7771` from the group `test-7771` but I can't.

**Expected behavior**
Expecting the core device can be removed from a non-existing thinggroup.

**Actual behavior**
Cannot remove the core device from a deleted thinggroup.

**Environment**
 - OS: Ubuntu 18.04
 - JDK version: JAVA 8
 - Nucleus version: 2.3.0

**Additional context**
Impact of the setting : Harder to manage a little bit.

**Comment by MikeDombo** [comment]
Hi Debo,
This is a known limitation which has already been fixed in the code base pending security testing and release.

Resolved by #977
