### ISSUE TITLE
(Nucleus): Support MQTT Persisted Sessions

### ISSUE THREAD

**Issue by crestid** [aws-greengrass/aws-greengrass-nucleus#1087]
**Feature Description**
Be able to configure Persistent Sessions on Nucleus similarly to how it is possible today in GGv1  (https://docs.aws.amazon.com/greengrass/v1/developerguide/gg-core.html#mqtt-persistent-sessions). 

**Use Case**
Manage the intermittent disconnection scenario - make sure that as soon as a device comes back online it will get the persisted messages destined to its subscriptions.

**Proposed Solution**
Replicate the behavior depicted in https://docs.aws.amazon.com/greengrass/v1/developerguide/gg-core.html#mqtt-persistent-sessions

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi there and thank you for your interest in Greengrass.

Greengrass V2 always connects to AWS IoT Core using a persistent connection. Is there some issue that you are seeing?

**Comment by MikeDombo** [comment]
Closing for no response and likely no action required.

Please reopen if needed.

**Comment by crestid** [comment]
Sorry Mike, I did not receive a notification on this comment.
So you mean that the connection that Greengrass v2 instantiates is always persistent? 
If a Component of my Core device will subscribe to a remote IoT Topic, and the device disconnects, will the messages be retrieved when the device reconnects?

**Comment by MikeDombo** [comment]
Yes, Greengrass V2 MQTT sessions are always persistent. Messages will be delivered according to the session persistence rules of AWS IoT Core.

**Comment by crestid** [comment]
Thanks, I had been given mixed answers and thought this feature was not present. This request can be closed and apologies
