### ISSUE TITLE
(Nucleus): support for HTTPS proxy

### ISSUE THREAD

**Issue by gadams999** [aws-greengrass/aws-greengrass-nucleus#1089]
**Feature Description**
Support for HTTPS proxy connections to protect credentials in the same way supported by Greengrass version 1.

**Use Case**
Proxy servers requiring authentication use the Basic method for providing username and password. Without HTTPS support these credentials are sent in the clear and can obtained by others on the network path. Providing HTTPS support removes the risk of credential exposure.

**Proposed Solution**
Enable HTTPS support in the same manner as Greeengrass version 1. Optionally provide the ability to use CA PEM file or keystore to allow the Nucleus to validate the presented server certificate. If the signing CA is not available, allow for overriding server certificate validation.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi Gavin,
This feature is coming soon!

Closed by #1078
