### ISSUE TITLE
(nucleus): apt error got ignored

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1091]
**Describe the bug**
If I deploy a component which will run `apt update` or `apt install $PACKAGE_NAME` with root privilege, sometimes the apt error will show in greengrass log
```
2021-07-14T16:00:10.422Z [WARN] (Copier) component-name: stderr. E: Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable). {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
2021-07-14T16:00:10.422Z [WARN] (Copier) component-name: stderr. E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?. {scriptName=services.burro-configurator.lifecycle.Bootstrap.Script, serviceName=burro-configurator, currentState=NEW}
```
And the deployment will stop here, but the deployment status will show `completed` in the end which I expected the non-zero status code should be caught and present as `Failed`

**To Reproduce**
Steps to reproduce the behavior. If possible, provide a minimal amount of code that causes the bug.
1. Create a component with `sudo apt update` or `sudo apt install $PACKAGE_NAME` 
2. Run `sudo apt update` locally and deploy the component you created in the first step.
3. Sometimes you will see it got blocked but the deployment status will show `completed`

**Expected behavior**
I expect APT error will get caught and present as `Failed`deployment status.

**Actual behavior**
It will ignore the APT error and show `Completed` no matter the apt command successful executed or not.

**Environment**
 - OS: [e.g. Ubuntu 18.04]
 - JDK version: Java 8
 - Nucleus version: 2.4

**Additional context**
What kind of error will be ignore by nucleus? (This apt error might be ignored by default, so I kinda want to know more about this)
If some errors aren't presented as `Failed` on deployment status by default, then I will not be able to manage the correctness of deployment status. But at least, I can prepare something for it if I already know some info.

**Comment by MikeDombo** [comment]
Hi,
Greengrass relies on the POSIX exit code of the command. The exit code is logged in the component log file, so you should see that in addition to the error logs. 
If the exit code is not zero then it is an error. For bootstrap, exit code 100 and 101 are also acceptable but have special meanings.

What is the exit code of your bootstrap step?

**Comment by DeboBurro** [comment]
It was 100. May I force bootstrap to make all non-zero exit code be `Failed`. Also what are the meanings of 100 and 101 to bootstrap?

**Comment by MikeDombo** [comment]
Why was it 100? What is the full bootstrap script that you wrote?

**Comment by DeboBurro** [comment]
Generally, the bootstrap script is `/bin/bash test.bash` and the code inside the test.bash is `sudo apt update`.
Sometimes, another process was using the `apt install` so the other process trying to use `apt` command will be blocked. 
The exit code of apt update fail will be 100 so I am not sure why nucleus intentionally ignore this error code. 
Example:
```
root@HOSTNAME:~# apt update
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
root@burro-7-771:~# echo $?
100
```

**Comment by MikeDombo** [comment]
In the bootstrap script and only the bootstrap script, Greengrass assigns special meaning to exit code 100 and 101. 
I can suggest to you two things. 1) Do not use the bootstrap script unless you have a reason to use it. The reasons to use it are either if you want to restart the device or restart the Greengrass Nucleus. To signal either of these situations you would use those special exit codes (100 to restart Greengrass, 101 to restart the device). [See the Greengrass recipe documentation](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html) for more information. 2) Translate the exit code from APT in your script; if it exits 100 or 101 then your script must exit with a different code. You can of course print the real exit code into the logs like `echo $?`.

**Comment by DeboBurro** [comment]
Thanks Mike. I might need to handle these error codes myself for now. And I have some questions. What's the most use cases when people using greengrass? Do most of the people use nucleus to configure devices? or in your opinion, is there a better AWS tool to configure 100+ devices ( like apt package, software and firmware update all together).

**Comment by MikeDombo** [comment]
If you're just trying to manage a fleet of devices then Greengrass isn't really the solution for you. The better solution would be AWS Systems Manager. 
https://docs.aws.amazon.com/systems-manager/latest/userguide/what-is-systems-manager.html

**Comment by DeboBurro** [comment]
Thank you so much Mike, I won't consider this as an issue. It's an error from user's use case. Feel free to close this thread.

**Comment by MikeDombo** [comment]
Will do, good luck with your work on this.
