### ISSUE TITLE
(nucleus): Remove container images downloaded via `docker:` artifacts when the component is removed

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-nucleus#1111]
**Feature Description**
When a component that has specified artifacts using the `docker:` key is removed, the DockerApplicationManager plugin should remove the image if no other deployed component requires it

**Use Case**
Edge devices are limited in resources, and removing unused artifacts is a best practice

**Proposed Solution**
The only workaround is to write a custom component that monitor the images and removes those for which there are no running containers. 

**Other**

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by shaguptashaikh** [comment]
Hi @massi-ang, thanks for this reminder, we are currently thinking about providing a generic cleanup/uninstall mechanism requested by customers which can help clean up artifacts/installations like images. We will update here once we're able to work on that.
