### ISSUE TITLE
(nucleus docker plugin): "The stub received bad data" when logging into docker with IAM token

### ISSUE THREAD

**Issue by FMauroy** [aws-greengrass/aws-greengrass-nucleus#1140]
**Describe the bug**
On Greengrass 2.5 on Windows, we receive "The stub received bad data" when nucleus tries to use the IAM credentials it just acquired to login to a private docker repo in ECR.

**To Reproduce**
This works: `aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin XXXXXXX.dkr.ecr.eu-central-1.amazonaws.com`.

When nucleus does it by itself, we have this:
`2021-11-25T13:29:14.783Z [INFO] (pool-2-thread-5) com.aws.greengrass.tes.CredentialRequestHandler: Received IAM credentials that will be cached until 2021-11-25T14:24:14Z. {iotCredentialsPath=/role-aliases/GreengrassV2TokenExchangeRoleAlias/credentials}
2021-11-25T13:29:17.009Z [INFO] (pool-2-thread-5) com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader: docker-login. task failed and will be retried. {task-attempt=1, componentIdentifier=com.XXXXXXX, artifactUri=docker:XXXXXXX.dkr.ecr.eu-central-1.amazonaws.com/XXXXXXX:windows-latest}
com.aws.greengrass.componentmanager.plugins.docker.exceptions.DockerLoginException: Error logging into the registry using credentials - WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error saving credentials: error storing credentials - err: exit status 1, out: 'The stub received bad data.'
        at com.aws.greengrass.componentmanager.plugins.docker.DefaultDockerClient.login(DefaultDockerClient.java:82)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.lambda$performDownloadSteps$1(DockerImageDownloader.java:182)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.runWithConnectionErrorCheck(DockerImageDownloader.java:242)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.lambda$run$3(DockerImageDownloader.java:231)
        at com.aws.greengrass.util.RetryUtils.runWithRetry(RetryUtils.java:50)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.lambda$run$4(DockerImageDownloader.java:231)
        at com.aws.greengrass.util.RetryUtils.runWithRetry(RetryUtils.java:50)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.run(DockerImageDownloader.java:228)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.performDownloadSteps(DockerImageDownloader.java:180)
        at com.aws.greengrass.componentmanager.plugins.docker.DockerImageDownloader.download(DockerImageDownloader.java:90)
        at com.aws.greengrass.componentmanager.ComponentManager.prepareArtifacts(ComponentManager.java:430)
        at com.aws.greengrass.componentmanager.ComponentManager.preparePackage(ComponentManager.java:377)
        at com.aws.greengrass.componentmanager.ComponentManager.lambda$preparePackages$1(ComponentManager.java:338)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`.

Also note the warning about the usage of passwords in the command line. Could this be a real security issue? I did't see the output in clear text.

**Expected behavior**
Nucleus succeeds in login into the private docker repo and downloads the latest image. Also, no warning appears about a potential security risk.

**Actual behavior**
Login fails and a security warning appears.

**Environment**
 - OS: Windows 10 Enterprise (19042.1348)
 - JDK version: 1.8.0_312-b07
 - Nucleus version: 2.5
 - Docker Desktop: 4.2.0 (70708) - Engine: 20.10.10 - Credential Helper: 0.6.4

**Additional context**
Kash Patel referenced this existing issue: https://github.com/aws/aws-cli/issues/5636
But in our case, the token/password is not longer than 2500, it stays around 1800 characters.

Thanks for any tip or idea (or solution) :-)

**Comment by MikeDombo** [comment]
Hello @FMauroy,
When you say that the password generated is only around 1800 characters, how do you know that?

When you run aws ecr-login, this is not the same thing that Greengrass is doing. Greengrass calls the ECR [getAuthorizationToken API](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/99e0ac7197cdc9dc04de42417eb8c052e82afb7e/src/main/java/com/aws/greengrass/componentmanager/plugins/docker/EcrAccessor.java#L79). And then uses [`docker login -u <user> -p <password>`](https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/4c3b16588b7695d69bf370d1c873df92343d6fdf/src/main/java/com/aws/greengrass/componentmanager/plugins/docker/DefaultDockerClient.java#L61). Additionally, Greengrass is using temporary credentials which are provided through the IoT Credential Provider service, so if you are not using those exact same credentials it isn't unreasonable that there is a different outcome.

The warning about using the password over the command line is not a security concern as Greengrass does not log the command anywhere and reading the command line value while the process is executing would require administrative privileges on the device.

Regarding the same issue referenced in the CLI repo, does the account which the Greengrass device is in have AWS SSO enabled?

**Comment by FMauroy** [comment]
Hi @MikeDombo, thanks for the quick reply.

I get a token of 1812 characters when I do `aws ecr get-login-password`. I supposed this would be the same one used by nucleus internally. How can you get the length of the token used by nucleus?

The customer where we have the issue doesn't have SSO enabled (yet). I tested the beta of GG 2.5 on my company's subscription, which has SSO, but that worked.

Is there a way to reduce the amount of detail passed in the JWT returned by IAM?

Looking forward to having more info from your internal request.

**Comment by MikeDombo** [comment]
The password length is most likely to increase when the credentials are short term credentials coming through the IoT Credentials Provider service. When I use get-login-password I also get roughly 1800 characters, but when using credentials from IoT it is 2700.
I don't see any obvious way to cut down on the length, so I'm hoping that my request to ECR will be helpful for that.

You could try some of the other workarounds mentioned in the CLI repo, I'm not sure if any of them are viable.

**Comment by MikeDombo** [comment]
I just started an EC2 instance with container support to test this out and I found that it does work with EC2's default setup.

How is docker configured on the customer device, are there any changes aside from just installing docker? To be specific, the `wincred` docker credential provider is not installed by default on the EC2 instance, so there is no wincred problem in that case since it doesn't even try to use that provider.

**Comment by MikeDombo** [comment]
So Docker cannot be configured to _not_ use wincred if the binary file docker-credential-wincred exists on the user's PATH. The only solution would be to remove/rename the docker-credential-wincred.exe file such that Docker cannot find it. The file should be located in `C:\Program Files\Docker\Docker\Resources\bin\docker-credential-wincred.exe`. 
You can run in powershell `get-command docker-credential-wincred` to find the path.

**Comment by FMauroy** [comment]
Thanks a  lot for the suggestion, I'll try that tomorrow morning and report back.
Cheers!

**Comment by FMauroy** [comment]
Thanks again, it works with this workaround. Not totally clean but it can work until a real solution is found. Did you get any feedback from the ECR team?

**Comment by MikeDombo** [comment]
Hi, great to hear that that did work! I agree with you that it isn't the best.

I have spoken to some folks from ECR and they have no solutions that will work for Greengrass. I have opened a feature request with them to resolve the issue, but there is no timeline for that.

**Comment by MikeDombo** [comment]
https://github.com/aws/containers-roadmap/issues/1589

Please react to this issue on their roadmap with 👍 so that your vote will count when they prioritize feature requests.

**Comment by MikeDombo** [comment]
Since there is now another issue which you can track and because you have work around I will close out this issue as there isn't anything that Greengrass can do directly to address it.
