### ISSUE TITLE
(greengrass): cannot recover when Windows install was failed.

### ISSUE THREAD

**Issue by songlunzhao** [aws-greengrass/aws-greengrass-nucleus#1156]
**Describe the bug**
I am doing some testing on Greengrass Windows install. And I accidentally run the install command twice without deleting the Windows system service and Greengrass core device. After the second time run I got an error "Unable to set up Nucleus as a system service". Then I deleted the GG system service, GG core device and re-started Windows, but I start getting the same error in every time on my install.

**To Reproduce**
1. as Administrator run
java -Droot="C:\greengrass\v2" "-Dlog.store=FILE" -jar ./GreengrassInstaller/lib/Greengrass.jar  --init-config ./config.yaml --component-default-user ggc_user --setup-system-service true
the install was success and GG system service is up and running.
2. run the same command again and I got GG "Unable to set up Nucleus as a system service".
3. delete system service, delete core device and re-start Windows
sc stop "greengrass"
sc config "greengrass" start=disabled
sc delete "greengrass"
rmdir /s /q C:\greengrass\v2
aws greengrassv2 delete-core-device --core-device-thing-name GreengrassCore
restart Windows
4. confirm GG device is deleted from AWS, system service is deleted, re-install GG, but got error "Unable to set up Nucleus as a system service". I can see the Windows system service is created but cannot be started
java -Droot="C:\greengrass\v2" "-Dlog.store=FILE" -jar ./GreengrassInstaller/lib/Greengrass.jar  --init-config ./config.yaml --component-default-user ggc_user --setup-system-service true

**Expected behavior**
After Step 4 I expect a GG system service is up and running.

**Actual behavior**
Tell us what actually happened.
GG system service is not starting
**Environment**
 - OS: [Windows Server 2016 on EC2]
 - JDK version: OpenJDK 11
 - Nucleus version: 2.5.3

**Additional context**

E.g. what is the impact of the bug?

**Comment by MikeDombo** [comment]
After @songlunzhao provided me access to the EC2 instance, I was able to resolve the issue by disabling the service in the services console, then making it automatic start again. This then allowed the service to start properly. Given this, it seems to be something silly in Windows rather than Greengrass itself.
