### ISSUE TITLE
effectiveConfig.yaml: Service restart dumps values

### ISSUE THREAD

**Issue by mjkmoynihan** [aws-greengrass/aws-greengrass-nucleus#1168]
**Describe the bug**
greengrass-cli and communication with aws greengrass console fail giving:
```
software.amazon.awssdk.eventstreamrpc.ServiceOperationMappingContinuationHandler: class java.lang.RuntimeException occurred while attempting to authN/authZ connect: Unrecognized client connecting to GGC over IPC. {}
java.lang.RuntimeException: Unrecognized client connecting to GGC over IPC
```

Values inside `effectiveConfig.yaml` have been erased e.g. 

```
system:
  certificateFilePath: ""
  privateKeyPath: ""
  rootCaPath: ""
  rootpath: "/greengrass/v2"
  thingName: ""
```

All of the valid certificates and keys are still present on the device in the expected locations. 

**To Reproduce**
Deployment was locked in a state of `Deployment is in a stage where it cannot be cancelled, need to wait for it to finish` and so the device was power cycled a couple of times with no observable change. The greengrass service was restarted manually as `sudo systemctl restart greengrass.service` after which the failure to connect to greengrass services began to appear. 

Attached logs show that the service restart triggered a dump of the effective config.

**Expected behavior**
Some way to restore default behaviour to a device when deployments fail without having to trigger service restart

**Actual behavior**
device was stuck in cycle of attempting to cancel a deployment. greengrass service was restarted and triggered a config dump which rendered the edge device unable to issue greengrass-cli commands or communicate with aws greengrass console 

**Environment**
 - OS: Ubuntu 18.04
 - JDK version: openjdk version "11.0.14.1" 2022-02-08 LTS
 - Nucleus version: 2.5.3

**Additional context**
We currently use a bastion server to ssh into our remote devices but would prefer to use aws secure tunnelling component. If this event happens again on a device without alternative ssh access then it would be rendered unreachable. 

[gg_config_dump.log](https://github.com/aws-greengrass/aws-greengrass-nucleus/files/8184785/gg_config_dump.log)

**Comment by MikeDombo** [comment]
Hello @mjkmoynihan,
Can you please provide all of the files in the config directory and deployments directories?

The deployment which you were running, was that a local or a cloud deployment? If it was a cloud deployment, was rollback enabled?

**Comment by mjkmoynihan** [comment]
Hi @MikeDombo thanks for your reply. 

I have since reinstalled greengrass as we urgently needed the device to be working again so unfortunately I can't provide the contents of the config directory. 

The deployment was a cloud deployment and rollback was not enabled ( I wasn't aware of it at the time but will be using it in future!) Does this need to be enabled to generate the `rollback_snapshot.tlog` file? 

At the time the log was displaying the "cannot be cancelled" message I had been attempting to send new deployments from the cloud.

**Comment by MikeDombo** [comment]
For cloud deployments rollback is enabled by default, so I do believe that you had rollbacks enabled.

**Comment by mjkmoynihan** [comment]
Yes you are correct, I can see that rollback was likely enabled (I had thought otherwise based on the settings for another device but the deployment for the device in question had rollback enabled).  

I have logs from one of the custom components which showed it had entered the shutdown phase of it's lifecycle multiple hours before the deployment status was stuck: 
```
2022-03-03T08:51:15.258Z [WARN] (Copier) com.edge.TestbenchContainer: stderr. Error: No such container: cv_app_testbench. {scriptName=services.com.edge.TestbenchContainer.lifecycle.Shutdown, serviceName=com.edge.TestbenchContainer, currentState=BROKEN}
2022-03-03T08:51:15.266Z [WARN] (pool-2-thread-16) com.edge.TestbenchContainer: shell-runner-error. {scriptName=services.com.edge.TestbenchContainer.lifecycle.Shutdown, serviceName=com.edge.TestbenchContainer, currentState=BROKEN, command=["bash /greengrass/v2/packages/artifacts/com.edge.TestbenchContainer/0.1.56/shut..."]}
```
The output here refers to a shutdown script which attempted to kill a docker container which never started due to an error. A deployment was created at this time to remove this component and leave only aws.greengrass.Nucleus and aws.greengrass.cli deployed. 

I had assumed this deployment had executed with no issue until I created another one 6 hours later to find that the deployment cycle was stuck. 

[gg_log_3pm.log](https://github.com/aws-greengrass/aws-greengrass-nucleus/files/8186636/gg_log_3pm.log)

The above file is an extended version of the file I shared previously. Unfortunately I have no logs from the time issuing the deployment which removed the custom component that the deployment that could not be started.

**Comment by MikeDombo** [comment]
@mjkmoynihan what lifecycle phase caused com.edge.TestbenchContainer to become broken? Did it break during "install" or "startup"? What does the recipe for this component look like?

**Comment by MikeDombo** [comment]
We have identified several issues which we will work to address. 

Please do provide answers to my questions from the previous rely though if you're able. 

Thank you

**Comment by mjkmoynihan** [comment]
Hi @MikeDombo 

The TestbenchContainter component status became BROKEN during the shutdown phase of it's lifecycle. 

It's lifecycle looks like this 
```
"Lifecycle": {
          "Install": "bash {artifacts:path}/install.sh && python3 -u {artifacts:path}/download_assets.py",
          "Run": "bash {artifacts:path}/run.sh",
          "Shutdown": "bash {artifacts:path}/shutdown.sh"
        },
```

Install.sh runs `pip3 install --user boto3` and `pip3 install --user awsiotsdk` then proceeds to create some directories. 

run.sh contains the docker run command string 

finally, shutdown.sh contains only two lines 

```
docker kill cv_app_testbench 
docker container rm cv_app_testbench
```


The deployment which became stuck contained only this component, the greengrass-cli component and greengrass.nucleus


I unfortunately do not have any log for the deployment which became stuck. 

I'm on GMT timezone so apologies for any delays in reply. 

Thanks

**Comment by J-C-L** [comment]
Fix has been merged. You can build Nucleus from the main branch to verify that your issues have been solved. The fixes will also be in an upcoming release, though I do not have an ETA.
