### ISSUE TITLE
Boolean coercion has undesired effects on command-line argument processing

### ISSUE THREAD

**Issue by timmattison** [aws-greengrass/aws-greengrass-nucleus#1181]
### Expected behavior

Specifying the option `--deploy-dev-tools` or `--deploy-dev-tools true` should do the same thing

### Actual behavior

Specifying the option `--deploy-dev-tools` leaves the `deployDevTools` value set to `false`

### Consequence

If a user does this by accident they will not get an indication they've done something wrong, the value will be the opposite of what they expect, and there will be no messages in the output indicating that the command-line tools will or won't be installed.

This makes troubleshooting the issue challenging. Normally when the developer tools are not installed but the user requested them to be installed there is a warning that indicates the tools won't be installed because previous deployments exist.

### Background

I was trying to set up a new Greengrass system today and my command-line looked like this:

```
sudo -E $JAVA -Droot="$GREENGRASS_ROOT" -Dlog.store=FILE \
  -jar ./GreengrassInstaller/lib/Greengrass.jar \
  --aws-region us-east-1 \
  --thing-name "$THING_NAME" \
  --thing-group-name "$THING_GROUP_NAME" \
  --thing-policy-name GreengrassV2IoTThingPolicy \
  --tes-role-name GreengrassV2TokenExchangeRole \
  --tes-role-alias-name GreengrassCoreTokenExchangeRoleAlias \
  --component-default-user ggc_user:ggc_group \
  --provision true \
  --setup-system-service true \
  --deploy-dev-tools
```

`--deploy-dev-tools` was missing the `true` option after it due to a copy and paste issue on my side.

I would expect this flag to either set the value to `true` or to report an error that a value needs to be specified. Normally when a flag can be specified the user expects the affirmative version `--deploy-dev-tools` to set the value to `true` and the negative version `--no-deploy-dev-tools` to set the value to `false`.

This line of code appears to be the culprit that is setting the value to `false`:

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/34c2fe952486bf8cb171d06619e428fc8434ea4c/src/main/java/com/aws/greengrass/easysetup/GreengrassSetup.java#L451

It appears that the `Coerce.toBoolean` method is used outside of just the Greengrass setup so I don't know if its behavior can be changed easily.

Instead it might be easier to rework the command-line processing code to use a library that handles this automatically like [picocli](https://picocli.info/).

**Comment by timmattison** [comment]
It looks like adding picocli as a dependency appears to increase the output JAR size by ~400k.

**Comment by J-C-L** [comment]
Thank you for pointing out the issue. We will look into possible solutions.
