### ISSUE TITLE
(nucleus): enable user to ssh into the edge device through greengrass

### ISSUE THREAD

**Issue by DeboBurro** [aws-greengrass/aws-greengrass-nucleus#1195]
**Feature Description**
Let people ssh into the edge device through greengrass.service.

**Use Case**
When people want to debug remotely or when something wrong on the edge device that need engineers to go into it to fix.

**Proposed Solution**
option 1. Have an instance runs on AWS IoT cloud service. Have greengrass service setup a ssh tunnel to the instance. Let user be able to connect to the instance and ssh into the edge device.

option 2. Create a greengrass component to set the ssh connection to any instance on our own

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi @DeboBurro,
Greengrass offers 3 ways to do this. 

1. Secure Tunneling: https://docs.aws.amazon.com/greengrass/v2/developerguide/secure-tunneling-component.html
2. Systems Manager: https://docs.aws.amazon.com/greengrass/v2/developerguide/systems-manager-agent-component.html
3. Write your own component with the required log.

Closing this issue as it is not appropriate for discussion in this forum. Please use https://repost.aws/
