### ISSUE TITLE
Greengrass Component Cannot Subscribe to IPC Topic

### ISSUE THREAD

**Issue by gearoid-moore** [aws-greengrass/aws-greengrass-nucleus#1201]
**Describe the bug**
Component Description:
Subscribes to IPC messages on an "event" topic, which are published by another Greengrass component. 

After deploying a component to a device, the component was unable to subscribe to any stream topic. Un-deploying and re-deploying that individual component did not resolve the issue. 

Un-deploying all of the components to the thing and re-deploying them one-by-one seemed to resolve the issue. 

Component Log:
```
2022-04-11T11:46:28.597Z [INFO] (Copier) componentName: stdout. Successfully subscribed to topic: event. {scriptName=services.componentName.lifecycle.Run, serviceName=componentName, currentState=RUNNING}
2022-04-11T11:46:28.599Z [WARN] (Copier) componentName: stderr. INFO:root:Subscribe to topic stream closed.. {scriptName=services.componentName.lifecycle.Run, serviceName=componentName, currentState=RUNNING}
```

Component Config:
```
{
  "accessControl": {
    "aws.greengrass.ipc.pubsub": {
      "componentName:pubsub:1": {
        "policyDescription": "Subscribe access to all IPC topics",
        "operations": [
          "aws.greengrass#SubscribeToTopic"
        ],
        "resources": [
          "*"
        ]
      }
    }
  }
}
```

**To Reproduce**
Steps to reproduce the behavior. If possible, provide a minimal amount of code that causes the bug.

**Expected behavior**
The component would be able to subscribe to the IPC topic without closing the stream.

**Actual behavior**
The component cannot subscribe to the stream topic, log above. 

**Environment**
 - OS: Ubuntu 18.04
 - JDK version: openjdk version "11.0.14.1" 2022-02-08 LTS
 - Nucleus version: 2.5.3

**Additional Context**
None

**Comment by MikeDombo** [comment]
Hi @gearoid-moore,

Can you please provide the Greengrass logs for the time of the failure? Can you also explain what the failure was? You said "the component was unable to subscribe to any stream topic", how do you know this, is there a specific error?

**Comment by gearoid-moore** [comment]
Hi Mike,

The failure in the component is as specified in the logs above. The code to subscribe to the IPC messages is the sample code provided by AWS. The component waits until it receives a message (triggered by receipt of an "event" message), but as the topic stream is closed, the component is stuck at "Event Stream Closed". 

The component name has been anonymised for upload to Github - the component policy name is unique, each component has a different access control policy ID. 

Will upload logs shortly.

**Comment by MikeDombo** [comment]
Because it worked when you removed the components I think this is your issue.

If you were changing the access control configuration by creating a new version of your component with updated `DefaultConfiguration`, then that also easily explains the issue. Changing default configuration will have no effect until you perform a deployment to reset the configuration to the new defaults. See https://docs.aws.amazon.com/greengrass/v2/developerguide/update-component-configurations.html#reset-configuration-update

**Comment by MikeDombo** [comment]
Given your statements, I believe that this isn't a bug and that you should now have the required information to update access control in the future. 

Closing the issue. Please reopen if needed.
