### ISSUE TITLE
aws.greengrass.SNS: Fails for FIFO topics

### ISSUE THREAD

**Issue by mccauleyp** [aws-greengrass/aws-greengrass-nucleus#1221]
**Describe the bug**
Not sure where else to raise this issue, apologies if this is in the wrong place! 

I'm using the `aws.greengrass.SNS` component version `2.1.0` and found that it's not possible to publish to a FIFO topic. Perhaps there's something more to it, but I think the issue may simply be that there's an upfront regex validation of the Topic ARN that rejects the request if there's a dot `.` in the string. FIFO topic names [must end](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html#aws-properties-sns-topic-properties) in ".fifo". The [SNS Connector docs](https://docs.aws.amazon.com/greengrass/v1/developerguide/sns-connector.html) include:

 > Valid pattern: arn:aws:sns:([a-z]{2}-[a-z]+-\d{1}):(\d{12}):([a-zA-Z0-9-_]+)$

**To Reproduce**
Try using the `aws.greengrass.SNS` component to publish to a FIFO topic. 

**Expected behavior**
The SNS component should be able to publish to FIFO topics.  

**Actual behavior**
Trying to use a "*.fifo" topic ARN results in the following error: 

```
'{'response': {'status': 'fail', 'error_message': 'SNS arn does not follow the format arn:aws:sns:region:account-id:topic-name', 'error': "<class 'ValueError'>"}, 'id': '1234'}'
```

**Environment**
 - OS: AL2
 - JDK version: 11
 - Nucleus version: 2.5.5
 - aws.greengrass.SNS version: 2.1.0

**Comment by mccauleyp** [comment]
On further thought, I think this is more of a feature request, as FIFO topics require a `MessageGroupId` to be passed during the publish and may require a `MessageDeduplicationId` if the topic does not have `ContentBasedDeduplication` set.

**Comment by avipinku** [comment]
Hi,

Thanks for letting us know about this, we can see if we can add this as a feature request.

**Comment by avipinku** [comment]
We are tracking this internally, but since the `aws.greengrass.SNS` component is not open source, we can't track this here. Closing this.
