### ISSUE TITLE
(EasySetup): --setup-system-service true and --start false doesn't behave as expected

### ISSUE THREAD

**Issue by jmrtinb** [aws-greengrass/aws-greengrass-nucleus#1239]
**Describe the bug**
When setting `--setup-system-service true` and `--start false` the service is still started right away.

**To Reproduce**
Install greengrass using the options `--setup-system-service true` and `--start false`.

**Expected behavior**
Based on the documentation for these flags:
```
--setup-system-service,  -ss  (Optional) Specify true or false. If true, then the AWS IoT Greengrass Core software sets
itself up as a system service that runs when this device boots. The system service name is greengrass.
Defaults to false.
--start, -s  (Optional) Specify true or false. If true, the AWS IoT Greengrass Core software runs setup steps,
(optional) provisions resources, and starts the software. If false, the software runs only setup
steps and (optional) provisions resources. Defaults to true.
```
I expected `If false, the software runs only setup steps and (optional) provisions resources.` to mean that the service would be setup, but not started.

**Actual behavior**
Greengrass service is started right away.

**Environment**
 - OS: Ubuntu 20.04
 - JDK version: OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
 - Nucleus version: 2.5.6

**Comment by MikeDombo** [comment]
Closing as the pull request has been merged. This will be included in our next release (no ETA).
