### ISSUE TITLE
What is configure, recipe and status(FSS) for component?

### ISSUE THREAD

**Issue by overheat** [aws-greengrass/aws-greengrass-nucleus#1247]
**Feature Description**
There are some "TBD"/"TODO" in componentmanager documentation. Cloud you kindly complete it?

**Use Case**
There are few concept related to component, like configure, recipe and status(FSS).
Cloud you explain them in docs?

**Proposed Solution**
docs

**Other**
I can find docs like:
- CONFIGURE_COMPONENT_README.md
- README_CONFIG_SCHEMA.md
- src/main/java/com/aws/greengrass/componentmanager/COMPONENT_STORE_README.md

Cloud you explain more detail?

**Comment by junfuchen99** [comment]
Hello @overheat,

Thank you for your feedback. We will work to address the gaps in our componentmanager documentation. In the meantime, do you have any specific questions about component manager which blocks you?

**Comment by overheat** [comment]
I know that every component contains a recipe file. But I wonder to know does the recipe will be write into configure file eventually?  And will changing configure file change components behavior? How component manager mange components, both services, like FSS and standard GreengrassV2 components?

**Comment by MikeDombo** [comment]
Recipes are not written into the configuration, rather they are simply stored on disk in the recipes directory.

During a deployment, the lifecycle and configuration from recipes are merged into the active configuration: https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/main/src/main/java/com/aws/greengrass/deployment/DeploymentConfigMerger.java#L75

Editing the configuration file (config.tlog) will not have any impact on Greengrass until Greengrass restarts. Editing config.yaml or effectiveConfig.yaml will never have any effect.
