### ISSUE TITLE
System shutdown is delayed up to 90 seconds by greengrass service

### ISSUE THREAD

**Issue by grillbaer** [aws-greengrass/aws-greengrass-nucleus#1248]
**Describe the bug**
The greengrass systemd service needs up to 90 seconds to stop during the system shutdown. See screenshot below.
The greengrass.log file then shows several errors `com.aws.greengrass.mqttclient.MqttClient: Error unsubscribing`. See log file below.
Reason is that the system network may already have been shut down before the greengrass service is stopped.

**To Reproduce**
Shut down an Ubuntu system with the greengrass service installed by the greengrass installer.

**Expected behavior**
Fast and clean stop of the greengrass service at system shutdown.

**Actual behavior**
Delayed stop of the greengrass service at system shutdown until greengrass' MQTT/network timeouts or the systemd timeout run out.

**Environment**
 - OS: Ubuntu 20.04
 - JDK version: 11
 - Nucleus version: 2.5.5

**Additional context**

In my eyes the solution is to add the dependency `After=network.target` to the greengrass service definition. This will prevent stopping the network services before the greengrass service. See [systemd Network configuration synchronization points](https://systemd.io/NETWORK_ONLINE/).

I'll soon send a pull request for this suggested change.

The bug is not critical but unnecessarily prolongs system restarts.

Screenshot of shutdown logs:  
![greengrass-shutdown-delay-screenshot](https://user-images.githubusercontent.com/33845511/176406520-03d2c6d6-ab74-42bb-99c8-d9ee63e60642.png)

greengrass.log excerpt:
[greengrass.log](https://github.com/aws-greengrass/aws-greengrass-nucleus/files/9009356/greengrass.log).

**Comment by MikeDombo** [comment]
Hi @grillbaer,
Thank you for taking the time to submit this issue. Have you tried using Greengrass Nucleus 2.6.0 which was just released on Modnay? It changes some shutdown behavior and should speed it up for you.

**Comment by grillbaer** [comment]
Hi @MikeDombo,
Thank you for the hint. I just tested a while with Nucleus 2.6.0 and it indeed seems to stop faster even if the network is already down during greengrass shutdown. All my attempts were below 20 seconds while they often were over a minute with 2.5.5.

However, i think it still makes sense to enforce that greengrass stops _before_ the network stops. That behavior is what i think most developers assume when writing components.
