### ISSUE TITLE
Nucleus: Provide ability to relocate ipc.socket file

### ISSUE THREAD

**Issue by gadams999** [aws-greengrass/aws-greengrass-nucleus#1269]
**Feature Description**
Ability to relocate the `$GG_ROOT/ipc.socket` to another location on the filesystem, via initial configuration file.

**Use Case**
When running Greengrass in a container, and also running components as components that need to utilize the IPC, having `ipc.socket` in the `$GG_ROOT` location requires mapping the _entire_ directory structure (and sub-directories) as a docker volume to then make it accessible to the sibling component containers.

By allowing the file to be located in another directory, docker `volume` commands could then be specific to only mount that specific location.

**Proposed Solution**
Change the Nucleus to check for an initial config setting for the `ipc.socket` file location (e.g., `/tmp/greengrass/ipc.socket` or `/var/run/greengrass/ipc.socket`). During configuration, Greengrass will create the file within that directory, and then the container running the Greengrass Nucleus can make that available via a volume.

Components that run as containers on the same host can then map the exported volume to their namespace, and then use `AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT` to refer to the location within their containers for IPC use (along with the `SVCUID`). 

**Other**
Feature would reduce blast radius of a component by removing access to the full `GG_ROOT` directory structure.

* [ ] :wave: I may be able to implement this feature request
* [X] :warning: This feature might incur a breaking change

**Comment by junfuchen99** [comment]
Hello @gadams999,

Thanks for raising this, this is currently on our list of improvements we're tracking. We will update here once we make progress.
