### ISSUE TITLE
nucleus: Allow java distribution to be user defined, not reliant on environment

### ISSUE THREAD

**Issue by rpcme** [aws-greengrass/aws-greengrass-nucleus#1279]
**Feature Description**
Launch nucleus using system engineer defined JDK/JRE

**Use Case**
User may require use of java distribution other than the system distribution, or use a scaled down JDK in a user defined path that is not for general use by all apps on the system

**Proposed Solution**
Invocation is here (permalink)

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/c4cfe2bf8dace146556d2ddabd4dd90b474004f7/scripts/loader#L40

Example:

```bash
  $JAVA_EXE -Dlog.store=FILE ${JVM_OPTIONS} -jar "$LAUNCH_DIR/distro/lib/Greengrass.jar" ${OPTIONS} &
```

and launcher invoked by

```bash
JAVA_EXE=/path/to/my/java launcher...
```

Ideally definable when setting up systemctl

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi Richard,
Thank you for the suggestion. This is technically already possible to achieve by setting the PATH environment variable in an appropriate way to use your selected Java version.

In any case, this would be relatively simple to add as you've suggested, and we'd be happy to receive a PR to address this issue.
