### ISSUE TITLE
{iot:thingName} recipe variable not working

### ISSUE THREAD

**Issue by argandas** [aws-greengrass/aws-greengrass-nucleus#1366]
**Describe the bug**
The {iot:thingName} recipe variable is not working for the MQTT proxy access control options

**To Reproduce**
Create a component with access control options to publish to a topic using the {iot:thingName} recipe variable"
```json
"accessControl": {
    "aws.greengrass.ipc.mqttproxy": {
        "gg.com.example:mqttproxy:1": {
            "operations": ["aws.greengrass#PublishToIoTCore"],
            "resources": [
                "myTopic/debug/{iot:thingName}/#",
                "myTopic/data/{iot:thingName}/#"
            ]
        }
    }
}
```
**Expected behavior**
The device shall be able to publish to the following topics:
- myTopic/debug/{iot:thingName}/somedata
- myTopic/debug/{iot:thingName}/otherdata
- myTopic/data/{iot:thingName}/sensor1/param1
- myTopic/data/{iot:thingName}/sensor2/param2

**Actual behavior**
Not Authorized, when trying to publish the system throws an error message in /greengrass/logs/greengrass.log:
```log
2022-11-21T06:01:28.255Z [INFO] (Thread-3) com.aws.greengrass.builtin.services.mqttproxy.MqttProxyIPCAgent: Not Authorized. {error=Principal gg.com.example is not authorized to perform aws.greengrass.ipc.mqttproxy:aws.greengrass#PublishToIoTCore on resource myTopic/debug/thing_544553540a6f/somedata}
```
where:
Thing name = thing_544553540a6f, got it from environment variable "AWS_IOT_THING_NAME"

**Environment**
 - OS: Ubuntu 20.04
 - JDK version: 
   - openjdk version "11.0.15" 2022-04-19
   - OpenJDK Runtime Environment (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
   - OpenJDK 64-Bit Server VM (build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1, mixed mode)

 - Nucleus version: 2.7.0

**Comment by argandas** [comment]
Based on GG documentation, this recipe variable should work.
https://docs.aws.amazon.com/greengrass/v2/developerguide/ipc-iot-core-mqtt.html#ipc-operation-publishtoiotcore

But is not clear if is it possible to use it along with wildcards such as "#"

**Comment by argandas** [comment]
Also tried to set "interpolateComponentConfiguration" to true in the Nucleus configurations.
As suggested here: https://docs.aws.amazon.com/greengrass/v2/developerguide/greengrass-nucleus-component.html

**Comment by MikeDombo** [comment]
You must set interpolateComponentConfiguration to true in a deployment, _then_ you can use variables. interpolateComponentConfiguration must be set in a deployment prior to when you deploy the configuration that you want to interpret.

**Comment by MikeDombo** [comment]
Please see the explanation in the answer here: https://repost.aws/questions/QURIWPqzHlT3KUkn-On3QD0Q/greengrass-recipe-variables-in-component-configuration-nucleus-2-7-0.

Closing as assumed resolved. Reopen as needed.
