### ISSUE TITLE
lifecycle: Add support of `Lifecycle.Install` multiple Script items with different privileges

### ISSUE THREAD

**Issue by vladas-tamosaitis-tfs** [aws-greengrass/aws-greengrass-nucleus#1409]
**Feature Description**
Allow component multiple installation scripts with different privileges. Currently, according to the doc, `Install` is an object or string that defines the script to run.

**Use Case**
I think it is useful to be able to have a recipe like this

```json
{
  ...
  {
      "Platform": {
        "os": "windows"
      },
      "Lifecycle": {
        "Install": [
          {
            "RequiresPrivilege": "true",
            "Script": "icacls \"{artifacts:decompressedPath}\\artifacts\" /grant ggc_user:(OI)(CI)F /T"
          },
          {
            "Script": "py -3 -m pip install --user {artifacts:decompressedPath}\\artifacts\\"
          }
        ]
      },
      "Artifacts": [
        {
          "URI": "s3://some_path/artifacts.zip",
          "Unarchive": "ZIP"
        }
      ]
    }
}
```
**Proposed Solution**
This request might affect not only the `Install` section but probably the `Shutdown` also.

Old behavior when the `Install` section is an object should be preserved.

Install script exit code can be the sum of the separate scripts exit codes (could make it hard to debug though) or consider component as installed if all script items exit codes are 0.

`Skipif`, `Timeout`, `Setenv` should keep their behavior for each item

**Comment by MikeDombo** [comment]
Hi @vladas-tamosaitis-tfs,
Thank you for the suggestion.

You are changing permissions on the artifact decompressed path, this is not supported by Greengrass. You must use the permissions as set by Greengrass. If you wish to allow reading or executing, you can do this with artifact permissions: https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-format:~:text=An%20object%20that%20defines%20the%20access%20permissions%20to

The artifact directory must not be written to. If you want to write anywhere, you must use the component's work directory.

**Comment by sudhirjena** [comment]
@MikeDombo,

One thing which is not clear from [Recipe reference](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html) and [Recipe variables](https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-variables) is what is the order of precedence between `Lifecycle.Install` script vs `Artifacts.Unarchive`?

I publish my python greengrass component as one zipped artifact into a S3 bucket. This zipped artifact contains `requirements.txt`. But in my `Lifecycle.Install` script when I reference:

```
python3.9 -m pip install --prefer-binary --requirement {artifacts:decompressedPath}/requirements.txt
```

I get an error `stderr. ERROR: Could not open requirements file: [Errno 2] No such file or directory`

Are the decompressed artifact files available for `Lifecycle.Install` to use?

**Comment by MikeDombo** [comment]
@sudhirjena 

Yes, they certainly are if you have configured the artifact to be unarchived. That didn't work because you did not put the correct path.

https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html#recipe-variables

> Each artifact unzips to a folder within the decompressed path, where the folder has the same name as the artifact minus its extension. For example, a ZIP artifact named models.zip unpacks to the {artifacts:decompressedPath}/models folder.

**Comment by sudhirjena** [comment]
Thanks @MikeDombo,
I will check and confirm on this thread.
