### ISSUE TITLE
Nucleus: install Greengrass software without specifying thing name

### ISSUE THREAD

**Issue by vmyron** [aws-greengrass/aws-greengrass-nucleus#1523]
**Feature Description**
Decouple Greengrass software installation and provisioning/connection it to Thing. Local installation should have capability to run local component deployments and provisioning/connection to Thing.

**Use Case**
I want to develop custom Greengrass component that will be responsible to obtain somehow Thing details (name, group, roles, certificates, etc) and then link local running Greengrass software with this Thing.

**Proposed Solution**
Allow installation and run of Greengrass software in "local mode" with possibility to use Greengrass CLI for local deployments and connecting to Cloud on-demand.

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Greengrass can run without a thing name, but the you would not be able to deploy to it since it is not connected to the cloud.

You can see our documentation here for doing a custom provisioning: https://docs.aws.amazon.com/greengrass/v2/developerguide/custom-provisioning.html.

Hope this helps

**Comment by vmyron** [comment]
Thank you @MikeDombo.
I can't see how custom provisioning can help. I need exactly deploy without connection to the cloud. My custom component is going to wait for some event to happen and then connect Greengrass software to the cloud based on the data from event.

**Comment by MikeDombo** [comment]
> My custom component is going to wait for some event to happen and then connect Greengrass software to the cloud based on the data from event.

This sounds like custom provisioning to me. Your component would implement the provisioning interface, Greengrass would execute it on startup and then your component would wait for the event. Once it receives the event, it provides the provisioning information to Greengrass and then Greengrass will be able to connect to AWS IoT and receive cloud-based deployments.

You can make local deployments using the Greengrass local CLI component: https://docs.aws.amazon.com/greengrass/v2/developerguide/greengrass-cli-component.html are you aware of this component?

**Comment by vmyron** [comment]
Thank you @MikeDombo.
It looks now that it could be a case. 
So this could be closed
