### ISSUE TITLE
(nucleus): add NSS key log support 

### ISSUE THREAD

**Issue by artu-ole** [aws-greengrass/aws-greengrass-nucleus#1571]
**Feature Description**
Support logging of SSL/TLS session keys in NSS key log format for nucleus external communications.

**Use Case**
This is an essential feature for auditing and deeper troubleshooting of IoT device traffic.

**Proposed Solution**
Many applications support this behavior via SSLKEYLOGFILE environment variable, others have their own mechanisms, like an upstream s2n-tls library which accepts a callback function. This might require changes from several upstream aws libraries which might be neglecting that capability at this point.

**Other**
https://github.com/aws/s2n-tls/pull/2584
https://datatracker.ietf.org/doc/draft-thomson-tls-keylogfile/

**Comment by MikeDombo** [comment]
Hello,

Greengrass itself (the stuff in this repository) does not perform any cryptographic operations. It instead relies on both Java and the AWS IoT Device SDK. I would request that you make an issue in the device SDK to support this here: https://github.com/aws/aws-iot-device-sdk-java-v2/issues.

For the Java based operations, I do not see that Java itself supports NSS right now however there do seem to be some third party options that can convert Java's debug format into NSS; this is certainly something which you can use today with Greengrass if you enable Java's TLS debugging.

**Comment by artu-ole** [comment]
> It instead relies on both Java and the AWS IoT Device SDK.

Yeah, that's what I mean with "This might require changes from several upstream aws libraries which might be neglecting that capability at this point.". Since when it comes to the meaningful aws-greengrass-nucleus external communications the aws-iot-device-sdk-java-v2 is just a wrapper for [AWS Common Runtime](https://docs.aws.amazon.com/sdkref/latest/guide/common-runtime.html) in it of itself, which in-turn forms a graph of dependencies
![image](https://github.com/aws-greengrass/aws-greengrass-nucleus/assets/15938416/e9626ca5-652f-415c-aa26-be1d885a66aa)

out of which the cryptographic operations are done by the s2n library(which does support NSS key logging), hence projects like https://github.com/neykov/extract-tls-secrets are of no help(that was the first thing I've tried before realizing all of the above), that information is just not in the Java's debug at this point. I'm afraid issues that would need to be opened to all of those upstream repos would end up as stale without an overarching commitment to the NSS support on the amazon side, but I don't know if you are willing to make such a commitment.

**Comment by MikeDombo** [comment]
Thank you for your reply. I certainly cannot speak for all of Amazon at this point, but Greengrass would be happy to expose the necessary hooks if our upstream dependencies had them. As you said, S2N does have the capability. Following up with the device SDK repository will be the best way to move this forward.

**Comment by artu-ole** [comment]
Thank you for a quick reply. That does look like the most sensible course of action, I will do that, mentioning this issue.

**Comment by MikeDombo** [comment]
Closing until functionality is available in device SDK.
