### ISSUE TITLE
Deployment failing 

### ISSUE THREAD

**Issue by wills721** [aws-greengrass/aws-greengrass-nucleus#1589]
**Describe the bug**
Deployment failing

**To Reproduce**
Using console to deploy new version

**Expected behavior**
Deployment should succeed

**Actual behavior**
Tell us what actually happened.

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - JDK version:
 - Nucleus version:

**Additional context**
I am getting this error I see in greengrass.log and I can't understand what is going on?

2024-03-24T20:17:32.277Z [ERROR] (pool-3-thread-20) com.aws.greengrass.deployment.DeploymentService: Deployment task throws unknown exception. {DeploymentId=arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:14, deployment-error-types=[], GreengrassDeploymentId=4b773d35-1d27-4ea0-9d79-7931959986b3, deployment-error-stack=[DEPLOYMENT_FAILURE], currentState=RUNNING, serviceName=DeploymentService}
java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "requirement" is null
        at com.vdurmont.semver4j.Requirement.buildNPM(Requirement.java:109)
        at com.aws.greengrass.deployment.DefaultDeploymentTask.lambda$getNonTargetGroupToRootPackagesMap$3(DefaultDeploymentTask.java:236)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at com.aws.greengrass.deployment.DefaultDeploymentTask.lambda$getNonTargetGroupToRootPackagesMap$4(DefaultDeploymentTask.java:234)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at com.aws.greengrass.deployment.DefaultDeploymentTask.getNonTargetGroupToRootPackagesMap(DefaultDeploymentTask.java:226)
        at com.aws.greengrass.deployment.DefaultDeploymentTask.call(DefaultDeploymentTask.java:115)
        at com.aws.greengrass.deployment.DefaultDeploymentTask.call(DefaultDeploymentTask.java:50)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

E.g. what is the impact of the bug?

**Comment by MikeDombo** [comment]
Hello,
It looks like your configuration on the device is malformed, leading to this error. 

Is this a new installation of Greengrass?
Did you copy configuration from an existing device?

Please provide the config/config.tlog file to debug and open a ticket with AWS support if you want to keep the file private.

**Comment by wills721** [comment]
Is relatively new yes -- may a week or two old.  I did at one point change the name of the thing by copying to a new device. 

This is what I see in tlog 

{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentRootPackages"],"W":"changed","V":["aws.greengrass.clientdevices.mqtt.Moquette","aws.greengrass.Cli","aws.greengrass.LogManager","com.thio.coredevice.thio-dataload","aws.greengrass.DiskSpooler","aws.greengrass.clientdevices.mqtt.Bridge","aws.greengrass.Nucleus"]}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentRootPackages"],"W":"changed","V":["aws.greengrass.clientdevices.mqtt.Moquette","aws.greengrass.Cli","aws.greengrass.LogManager","com.thio.coredevice.thio-dataload","aws.greengrass.DiskSpooler","aws.greengrass.clientdevices.mqtt.Bridge","aws.greengrass.Nucleus"]}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","GreengrassDeploymentId"],"W":"changed","V":"5d3440b6-8501-4a69-8925-c78d9d620e25"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","GreengrassDeploymentId"],"W":"changed","V":"5d3440b6-8501-4a69-8925-c78d9d620e25"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","ConfigurationArn"],"W":"changed","V":"arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:16"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","ConfigurationArn"],"W":"changed","V":"arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:16"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentType"],"W":"changed","V":"SHADOW"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentType"],"W":"changed","V":"SHADOW"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentStatus"],"W":"changed","V":"IN_PROGRESS"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentStatus"],"W":"changed","V":"IN_PROGRESS"}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720","DeploymentStatusDetails"],"W":"interiorAdded","V":null}
{"TS":1711314722726,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314722720"],"W":"removed","V":null}
{"TS":1711314737814,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814"],"W":"interiorAdded","V":null}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentId"],"W":"changed","V":"arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:16"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentId"],"W":"changed","V":"arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:16"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentRootPackages"],"W":"changed","V":["aws.greengrass.clientdevices.mqtt.Moquette","aws.greengrass.Cli","aws.greengrass.LogManager","com.thio.coredevice.thio-dataload","aws.greengrass.DiskSpooler","aws.greengrass.clientdevices.mqtt.Bridge","aws.greengrass.Nucleus"]}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentRootPackages"],"W":"changed","V":["aws.greengrass.clientdevices.mqtt.Moquette","aws.greengrass.Cli","aws.greengrass.LogManager","com.thio.coredevice.thio-dataload","aws.greengrass.DiskSpooler","aws.greengrass.clientdevices.mqtt.Bridge","aws.greengrass.Nucleus"]}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","GreengrassDeploymentId"],"W":"changed","V":"5d3440b6-8501-4a69-8925-c78d9d620e25"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","GreengrassDeploymentId"],"W":"changed","V":"5d3440b6-8501-4a69-8925-c78d9d620e25"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","ConfigurationArn"],"W":"changed","V":"arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:16"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","ConfigurationArn"],"W":"changed","V":"arn:aws:greengrass:us-east-2:747601184933:configuration:thing/thio-dataload-core:16"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentType"],"W":"changed","V":"SHADOW"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentType"],"W":"changed","V":"SHADOW"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatus"],"W":"changed","V":"FAILED"}{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatus"],"W":"changed","V":"FAILED"}
{"TS":1711314737823,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails"],"W":"interiorAdded","V":null}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails","deployment-failure-cause"],"W":"changed","V":"Cannot invoke \"String.isEmpty()\" because \"requirement\" is null"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails","deployment-failure-cause"],"W":"changed","V":"Cannot invoke \"String.isEmpty()\" because \"requirement\" is null"}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails","deployment-error-types"],"W":"changed","V":[]}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails","deployment-error-types"],"W":"changed","V":[]}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails","deployment-error-stack"],"W":"changed","V":["DEPLOYMENT_FAILURE"]}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814","DeploymentStatusDetails","deployment-error-stack"],"W":"changed","V":["DEPLOYMENT_FAILURE"]}
{"TS":1711314737927,"TP":["services","FleetStatusService","sequenceNumber"],"W":"changed","V":114}
{"TS":1711314737822,"TP":["services","DeploymentService","runtime","ProcessedDeployments","1711314737814"],"W":"removed","V":null}

**Comment by MikeDombo** [comment]
Can you please provide the complete config.tlog file? That one is not complete and I do need to see the whole thing to understand why the error is happening.

If you changed the thing name by editing config files manually, you may have introduced an error into the configuration. The simplest way to get back to a working state would be to delete all of /greengrass/v2 and reinstall.

**Comment by wills721** [comment]
Blowing it all away and reinstalled corrected it.  I did not change it manually -- just ran the aws command again

**Comment by MikeDombo** [comment]
Without the full config.tlog I won't be able to take any further action, closing for now. Please reopen as needed.
