### ISSUE TITLE
Recipe  change not deploying

### ISSUE THREAD

**Issue by wills721** [aws-greengrass/aws-greengrass-nucleus#1626]
**Describe the bug**
I have a change in the recipe of my green grass custom component part of my core device.  Just the recipe.  I revised and deployed however the change did not take effect on the core device.  I can see in config.tlog as well it did not take effect -- it did not download to the core device.  When I totally deleted green grass core device (in iOT and blowing away the folder) and reinstalled -- then it deployed the new recipe correctly. Any idea? 

**To Reproduce**
Change recipe and deploy

**Expected behavior**
A change to receipt 

**Actual behavior**
Tell us what actually happened.

**Environment**
 - OS: Rasppian
 - JDK version:
 - Nucleus version:

**Additional context**

E.g. what is the impact of the bug?

**Comment by jcosentino11** [comment]
It's really hard to say without logs.  Aside from looking at `config.tlog` how else were you validating?  Did the new component ever make its way to the device (one way to check would be to look for new component version via [gg cli](https://docs.aws.amazon.com/greengrass/v2/developerguide/gg-cli-component.html#component-details))?   Any errors in greengrass.log?

**Comment by tiancishen** [comment]
What exactly were you trying to change in your recipe?

**Comment by wills721** [comment]
Well,  I'm changing it all from the console.  If I change the DefaultConfiguration of the recipe (e.g. add a new version, change config) from the console under component it has no effect when deployed.  However,  if I modify the configuration during the Deploy phase (e.g. where the merge option comes up) this actually worked.  Its odd that AWS lets you change the receipt default config in a new version but then just ignores it.

**Comment by MikeDombo** [comment]
Hello,

That's explained in the troubleshooting here: https://docs.aws.amazon.com/greengrass/v2/developerguide/troubleshooting.html#update-component-configuration-to-default-configuration.

Default configuration is only the default. Once you have deployed a component it now has configuration set on the device; updates to the default configuration will not apply. To apply the new defaults, you must use reset in the deployment.

**Comment by wills721** [comment]
Yeah,  I found this out the hard way.  Thank you!
