### ISSUE TITLE
(FleetStatusService): Healthy state interval

### ISSUE THREAD

**Issue by fiLLLip** [aws-greengrass/aws-greengrass-nucleus#796]
**Feature Description**
Being able to set short intervals/threshold for healthy checks, like 10 minutes. IoT core devices being down for 24 hours could could be critical.

**Use Case**
Instead of implementing own service for health checks, using the output from `aws greengrassv2 list-core-devices` would be great. We would want a warning after 10-30 minutes. Customers will call complaining before the 24 hour mark if we don't want to build our own ping service.

**Proposed Solution**
Be able to set the threshold of what is healthy and not ourselves.

**Other**

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi and thanks for your interest in Greengrass!

We have considered this feature and we'll keep this issue open to track it for now.

Thanks for the feedback and have a great day.

**Comment by MikeDombo** [comment]
Following up, if you're wanting to understand if the device is online or offline, then you can easily get the connectivity information from AWS IoT Core using [Fleet Indexing](https://docs.aws.amazon.com/iot/latest/developerguide/managing-index.html).

**Comment by jbutler** [comment]
Hi @fiLLLip , a couple more follow up questions for you, in case Fleet Indexing isn't what you're looking for:

* What types of failure scenarios you are trying to detect?
* What action would you, as an operator (?), take to correct the issue?
  * E.g. reboot the device, deploy a new version of software, etc

**Comment by fiLLLip** [comment]
> Following up, if you're wanting to understand if the device is online or offline, then you can easily get the connectivity information from AWS IoT Core using [Fleet Indexing](https://docs.aws.amazon.com/iot/latest/developerguide/managing-index.html).

That would be the gist of it, I guess! I'll check it out 👍 If I understand it correctly, I can tap into the shadow here to react on connectivity status changes?

> * What types of failure scenarios you are trying to detect?

If the core has connectivity with the cloud, basically.

> * What action would you, as an operator (?), take to correct the issue?

Automatically show a warning/create an issue in their dashboard that the core is offline. If it comes online again, It could be nice to deploy the newest software if it was offline during previous deploy

**Comment by MikeDombo** [comment]
If you just want to be notified when devices go on/offline then you can subscribe to events as described here: https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html

The fleet indexing allows you to check the current status instead of needing to track the events yourself.

Regarding your last sentence, if the device is offline and then comes back it will indeed pick up any deployments (the last applicable deployment for each _thing_ or _thing group_) that it missed when it was offline.

**Comment by fiLLLip** [comment]
> If you just want to be notified when devices go on/offline then you can subscribe to events as described here: https://docs.aws.amazon.com/iot/latest/developerguide/life-cycle-events.html
> 
> The fleet indexing allows you to check the current status instead of needing to track the events yourself.
> 
> Regarding your last sentence, if the device is offline and then comes back it will indeed pick up any deployments (the last applicable deployment for each _thing_ or _thing group_) that it missed when it was offline.

Well, I guess this covers exactly what I need!

Btw very excited about the GGv2 launch! Only "down side" is that it covers exactly the issues our team spent the past two weeks developing solutions around, making the development obsolete before it was put in use 😄 Should have released at first day of re:invent 😃

**Comment by MikeDombo** [comment]
Since it sounds like we've answered all your questions I'll close this issue now.

**Comment by fiLLLip** [comment]
Still, it's kind of "misleading" that the cores "report" as healthy when this amount of time has passed:
![image](https://user-images.githubusercontent.com/1264369/102593064-ac40a080-4114-11eb-9cf0-abdfedd249e9.png)
This core has been taken offline and wiped, without AWSs knowing of course. But I wouldn't classify it as healthy :joy:
