### ISSUE TITLE
(easysetup): iam:CreatePolicy required, even though policy exists

### ISSUE THREAD

**Issue by fiLLLip** [aws-greengrass/aws-greengrass-nucleus#802]
**Describe the bug**
When adopting a new Greengrass Core, we need temp credentials to do a lot of things. I don't want those credentials to be able to create new IAM policies and roles, so I created them myself, since they are reused across all adoptions. But, I cannot do the adoption since I don't have iam:CreatePolicy rights.
https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/8a9bd022c7a1da82012eec4a006839d7b7e36f70/src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java#L399
Here you run createPolicy directly, and it will never answer that it already exists since we don't have permission to create.
I would propose running the getPolicy first for checking if it exists instead of relying on the error message.

**To Reproduce**
Run easysetup with minimal permissions

**Expected behavior**
It should say it exist and move on.

**Actual behavior**
```
Attaching TES role policy to IoT thing...
Error while trying to setup Greengrass Nucleus
software.amazon.awssdk.services.iam.model.IamException: User: arn:aws:sts::xxx:assumed-role/GreengrassCommissioningRole/tempcore-30293-setup is not authorized to perform: iam:CreatePolicy on resource: policy GreengrassV2TokenExchangeRoleAccess
```

**Environment**
 - OS: Raspbian Stretch
 - JDK version: OpenJDK8
 - Nucleus version: latest?

**Additional context**
I need to add very permissive permissions to a role that will be running in the first-run scripts of my embedded device to add it as a temp core device in greengrass.

**Comment by fiLLLip** [comment]
Workaround:

Add iam:CreatePolicy permission with the specific policy as resource :+1: 

```
              - Effect: Allow
                Action:
                  - "iam:CreatePolicy"
                Resource: !Ref GreengrassV2TokenExchangeRoleAccess
```

**Comment by shaguptashaikh** [comment]
Hi, thanks for reporting this. We are looking into it and will post an update here once done.

As you pointed out, at the moment `iam:createPolicy` is needed in the [minimum permissions for setting up the core](https://docs.aws.amazon.com/greengrass/v2/developerguide/install-greengrass-core-v2.html#provision-minimal-iam-policy) with the `--provision` option. While we work on eliminating the need for create permissions when some of the resources exist, you seem to have worked around it by scoping down the `iam:createPolicy` permission to just the specific policy, please let us know if you have any questions about that.

**Comment by MikeDombo** [comment]
Closed by PR #805. Will be released soon in our next patch.

**Comment by fiLLLip** [comment]
Got the changes now, and updated my commissioning role policy to just be allowed to fetch the specific policy, but I think there is a missing check here: https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/07ebae237cac1f5a142aefd06ae8723bea5303b3/src/main/java/com/aws/greengrass/easysetup/DeviceProvisioningHelper.java#L463

My policy don't allow Nucleus to get "random" policies, but only the one it needs. Now I'm getting a error that my role is not authorized to perform iam:GetPolicy in resource: policy arn:aws:iam::aws:policy/GreengrassV2TokenExchangeRoleAccess. So it doesn't try my supplied policy first, which is arn:aws:iam::<account_id>:policy/GreengrassV2TokenExchangeRoleAccess. And since the exception isn't catched, it crashes.

**Comment by MikeDombo** [comment]
Can you just update it to add access to both of those roles? We try the first one which is the style of AWS predefined policies because Greengrass should be adding a premade policy in the future.

**Comment by fiLLLip** [comment]
> Can you just update it to add access to both of those roles? 

Yes, I added that to my policy now to get it working, and now it works. It's just a "gotcha" I didn't expect and didn't understand before looking at the code.

**Comment by MikeDombo** [comment]
Understood, thank you for reporting this, we'll look into addressing it in future releases.

**Comment by shaguptashaikh** [comment]
Addressing it here https://github.com/aws-greengrass/aws-greengrass-nucleus/pull/868
