### ISSUE TITLE
com.aws.greengrass.util.Permissions: Needs to ignore symlinks

### ISSUE THREAD

**Issue by kris-sum** [aws-greengrass/aws-greengrass-nucleus#812]
**Describe the bug**
When deploying code components to greengrass that setup symlinks (e.g. pipenv creating a virtual environment for python dependencies), the package installer executes `Permissions.setArtifactPermissions` on that archive directory. This causes errors the second time the code is executed when files on the filesystem already exist and include symlinks to (for example) system libraries like python:

```
com.aws.greengrass.componentmanager.exceptions.PackageDownloadException: Failed to change permissions of component com.switchsystems.REDACTED1.0.14 artifact ComponentArtifact(artifactUri=s3://REDACTED1/artifacts_1.0.2.zip, checksum=PhlQGRzARtlZc4Y/RMZA67cadpo0nwzEFr8QoOjz64o=, algorithm=SHA-256, unarchive=ZIP, permission=Permission(read=OWNER, execute=NONE))
        at com.aws.greengrass.componentmanager.ComponentManager.prepareArtifacts(ComponentManager.java:412)
        at com.aws.greengrass.componentmanager.ComponentManager.preparePackage(ComponentManager.java:333)
        at com.aws.greengrass.componentmanager.ComponentManager.lambda$preparePackages$1(ComponentManager.java:316)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.FileSystemException: /greengrass/v2/packages/artifacts-unarchived/REDACTED/artifacts_1.0.2/.venv/include/python3.7m: Too many levels of symbolic links or unable to access attributes of symbolic link
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:96)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:254)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:276)
        at com.aws.greengrass.util.platforms.unix.UnixPlatform.lambda$setPermissions$10(UnixPlatform.java:382)
        at com.aws.greengrass.util.platforms.unix.UnixPlatform.setPermissions(UnixPlatform.java:411)
        at com.aws.greengrass.util.platforms.Platform.setPermissions(Platform.java:114)
        at com.aws.greengrass.util.Permissions.setArtifactPermission(Permissions.java:46)
        at com.aws.greengrass.util.Permissions.setArtifactPermission(Permissions.java:49)
        at com.aws.greengrass.util.Permissions.setArtifactPermission(Permissions.java:49)
        at com.aws.greengrass.util.Permissions.setArtifactPermission(Permissions.java:49)
        at com.aws.greengrass.componentmanager.ComponentManager.prepareArtifacts(ComponentManager.java:408)
```

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/95e68fa1b2be62116263601b580bbc571241081e/src/main/java/com/aws/greengrass/componentmanager/ComponentManager.java#L408

**The first time this runs, everything is fine.** 
My component then has a 'setup' lifecycle step which creates symlinks in `unarchivePath/.venv`. The next time a deployment comes along (e.g. a different component is modified) the exsting package is re-prepared, and the code executes on the existing files in `unarchivePath` , which then causes the error above.

**To Reproduce**

* Deploy a component to the core device
* On the core device's filesystem, create a symlink inside the /packages/artifacts/your-component which links to something external, e.g. `ln -s /usr/include/python3.7m ./include/python3.7m`
* Re-run a deploy to the device
 
**Expected behavior**
Permissions should be set

**Actual behavior**
FileSystemException is thrown as the script cannot set permissions on files outside of the artifacts directory when following symlinks

**Environment**
 - OS: Debian GNU/Linux 10 (buster)
 - JDK version: openjdk 11.0.9.1
 - Nucleus version: 2.0.3

**Proposed Fix**
This could be fixed by ignoring symlinks inside the function https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/95e68fa1b2be62116263601b580bbc571241081e/src/main/java/com/aws/greengrass/util/Permissions.java#L40

**Comment by MikeDombo** [comment]
Hi Kris,
Can you tell me how/why the artifacts are linked to something on the system? The artifacts are intended to be immutable (not writable) so you should not be allowed to be creating links from inside of the artifact directory. If you want a writable area, then use the current working directory that your script is run from. The CWD will be the work directory which is configured to be writable by your code.

**Comment by kris-sum** [comment]
I'm using pipenv to manage python dependencies, which creates files in the artifact directory under .venv.

I don't quite agree that the artifacts directory should be non-writable, as I'm assuming if you were deploying node scripts then the same would happen - npm would install module dependencies into node_modules. Same for PHP/composer packages. 

I was using pipenv in a different way which put the virtual environment files into hone/ggc_user/local/... But as there is no "uninstall" lifecycle step I can't clean up that directory when the component gets updated.

**Comment by MikeDombo** [comment]
The artifact directory _is_ non-writable. For Node, customers should be packaging the entire node_modules directory in the artifacts. You shouldn't be running any install commands on the device. Sort of like a docker container, the code should be packaged and ready to just run immediately.

What does your recipe look like? You can run pipenv inside of the work directory which is writable and should work as you expect.

**Comment by MikeDombo** [comment]
In this code: https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/73d41cf51ec9637308f3791c91fe724ef7c92368/src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java#L410

Which is where we are setting the permission according to the stacktrace, we have set Java to `NOFOLLOW_LINKS` so it won't be trying to set the permissions on the linked target, it should be setting permissions on the symlink itself which is the correct behavior. The fact that it is unable to do that is somewhat concerning though.

**Comment by kris-sum** [comment]
(thanks for looking at this @MikeDombo 🥇)

My recipe is as follows:

```
  Lifecycle:
    Install:
      Script: |-
        cd {artifacts:decompressedPath}/artifacts_1.0.0
        PIPENV_VENV_IN_PROJECT=1 pipenv sync
    Run: 
      Script: |-
        cd {artifacts:decompressedPath}/artifacts_1.0.0
        pipenv run python3 main.py
```

Does the work directory get cleaned up? I had a problem where I did so many deploys I had lots of virtual environments for each deployed version, filling up the device HDD.

I also didn't want to run into the situation where Component A and Component B have conflicting dependencies with different versions - which would work in a per-artifact directory setup, but not in a shared work directory.

**Comment by MikeDombo** [comment]
The work directory isn't shared, it is unique for each component. Currently it is not removed since removing it _might_ be deleting customer data that you'd expect us to keep. Though, eventually we'd probably have some options around that behavior. 

As for your recipe, thank you very much for sharing that's really helpful. Rather than cding into the artifact directory, since that is prone to have issues due to permissions, I'd suggest instead that you copy (or link) from the artifact path into the CWD (which is the work directory). Something like `ln -s {artifacts:decompressedPath}/artifacts_1.0.0} ./artifacts; cd artifacts; pipenv sync`

**Comment by kris-sum** [comment]
Many thanks @MikeDombo , I'll give that a try and will report back tomorrow.

Like you said, it's strange why it is throwing errors if it is already set to not follow symlinks :)

**Comment by MikeDombo** [comment]
Yes, I've looked through the OpenJDK codebase and it seems that error can occur even with NOFOLLOW_LINKS when the filesystem returns ELOOP which should mean that the symlink has a loop. Can you verify that the path in the error message definitely isn't part of a symlink loop?

**Comment by kris-sum** [comment]
It's not part of a symlink loop, that's the first thing I thought the problem was :) I will double-check tomorrow as well.

**Comment by kris-sum** [comment]
> 
> 
> I'd suggest instead that you copy (or link) from the artifact path into the CWD (which is the work directory). Something like `ln -s {artifacts:decompressedPath}/artifacts_1.0.0 ./artifacts; cd artifacts; pipenv sync`

✅ This symlink method worked great - pipenv syncs into the work directory `/greengrass/v2/work/com.switchsystems.xxxxxxx/artifacts/.venv` , I'll just have to be careful to clean it up and use different symlink targets for different versions of the code so that the dependencies don't overwrite each other when the component updates. Thanks Mike!
