### ISSUE TITLE
(recipe): Recipe variables from configuration does not work for setenv

### ISSUE THREAD

**Issue by fiLLLip** [aws-greengrass/aws-greengrass-nucleus#817]
**Describe the bug**
We have a recipe with a `Lifecycle.Run.Setenv.site: {configuration:/site}` that gets replaced with empty curly brackets, even though the configuration says `configuration.site: "labpml"`.

**To Reproduce**
Create a recipe with recipe variables in the Setenv section.

**Expected behavior**
`Lifecycle.Run.Setenv.site: {configuration:/site}` should be `Lifecycle.Run.Setenv.site: "labpml"` when `configuration.site: "labpml"`

**Actual behavior**
Output is `Lifecycle.Run.Setenv.site: {}`

**Environment**
 - OS: [e.g. Ubuntu 20.04]
 - JDK version:
 - Nucleus version: newest?

**Additional context**

E.g. what is the impact of the bug?
We cannot have deployment specific env vars

**Comment by MikeDombo** [comment]
I'm thinking this is an issue with your YAML since curly braces will be interpreted differently. Can you try wrapping it in quotes so that your yaml is something like:

```yaml
setenv:
  site: "{configuration:/site}"
```

**Comment by MikeDombo** [comment]
Closing issue after 7 days of inactivity.

If this is still a problem please let us know.
