### ISSUE TITLE
(com.aws.greengrass.util.orchestration.InitUtils): Greengrass Nucleus Fails to start in Docker Container

### ISSUE THREAD

**Issue by Shwetabh1** [aws-greengrass/aws-greengrass-nucleus#826]
**Describe the bug**
When executing the Greengrass jar inside a Docker container having an Ubuntu OS it fails with the following error:
Unable to set up Nucleus as a system service.

**To Reproduce**
1. Pulled a Docker Image having Ubuntu(18.04).
2. Entered into the container. 
2. Installed Java 11 on it.
3. Configured AWS Credentials.
4. Downloaded and installed GreenGrass Nucleus as specified [here.](https://docs.aws.amazon.com/greengrass/v2/developerguide/install-greengrass-core-v2.html)
`sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE -jar ./GreengrassCore/lib/Greengrass.jar \
    --aws-region us-east-1 --thing-name SECore \
    --component-default-user ggc_user:ggc_group --provision true --setup-system-service true --deploy-dev-tools true`
5. Install Fails with this error Unable to set up Nucleus as a system service.

**Expected behavior**
Install should be successful with the following message:
Successfully set up Nucleus as a system service

**Actual behavior**
Install Fails with this error Unable to set up Nucleus as a system service.

**Environment**
 - OS: Ubuntu 18.04 inside a docker container.
 - JDK version: 11
 - Nucleus version:  AWS IoT Greengrass Core software v2.0, latest nucleus.

**Additional context**
This is an experiment. I was successful in running the nucleus inside an ubuntu VM  but running the same inside a docker fails. I have attached the runtime logs and Greengrass error logs present under /greengrass/v2.
[greengrass_v2_error_logs.txt](https://github.com/aws-greengrass/aws-greengrass-nucleus/files/5857865/greengrass_v2_error_logs.txt)
[runtime_logs.txt](https://github.com/aws-greengrass/aws-greengrass-nucleus/files/5857866/runtime_logs.txt)

**Comment by MikeDombo** [comment]
Hi Shwetabh,
Greengrass cannot install as a system service within Docker since most Docker containers don't contain init systems. We're working on documentation for setting up Greengrass inside Docker.

**Comment by MikeDombo** [comment]
Please have a look at https://github.com/aws-greengrass/aws-greengrass-docker/ now.
