### ISSUE TITLE
PublishToTopicRequest: jsonMessage does not fully support JSON

### ISSUE THREAD

**Issue by cthulhuology** [aws-greengrass/aws-greengrass-nucleus#863]
The description of the aws.greengrass#PublishToTopic documentation states that:

jsonMessage

    (Optional) A JSON message. This object, JsonMessage, contains the following information:

    message

        The JSON message as an object.

The underlying model does not support anything other than objects which deserialize into a Map<String,Object>.  

https://github.com/aws/aws-iot-device-sdk-java-v2/blob/71fab934d591a4a3b9d1f70e66dfedadca019d70/sdk/greengrass/greengrass-client/src/event-stream-rpc-java/model/software/amazon/awssdk/aws/greengrass/model/JsonMessage.java#L30

The underlying protocol message is of the form:

{ "topic": "test/topic", "publishMessage" : { "jsonMessage": { "message" :  {"foo": "bar" }}}}

While using the current Java SDK forces you to supply a Map<String,Object>, this means components would be best served by sending other data structures such as arrays, strings, numbers, booleans, or null values need to wrap them in a JSON object, or send a binary message.

If  you send the message:

{"topic": "test/topic", "publishMessage": { "jsonMessage": { "message" : [ 1, 2, 3 ] }}}

Greengrass will return a result of "InternalServerError" as a raw value (unlike the typical empty json object response {}).   The reason for this is that the serviceModel.fromJSON() call 
throws an unexpected deserilization error when parsing the incoming message:

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/d65d4338fb208094c0e7edd63643d3144f126c28/src/main/java/software/amazon/awssdk/eventstreamrpc/OperationContinuationHandler.java#L269

This behavior both violates "the principle of least surprise" by having a "jsonMessage" IPC message that doesn't support valid JSON, and also by returning back an error message that does not conform to the same encoding as a successful request, as InternalServerError is not valid JSON.

It should also be noted that as the current design parses the full JSON payload prior to passing it to the IPC agent, this means that each payload is de-serialized and re-serialized when passing through the RPC layer.  This is rather wasteful from a resource utilization perspective, and can substantially increase the runtime memory requirements for high message volume applications.

**Comment by MikeDombo** [comment]
Hi,
Can you please open this issue in the [SDK repository](https://github.com/aws/aws-iot-device-sdk-java-v2/)? 

Thank you.
