### ISSUE TITLE
SubscribeToTopic:  blobs are mutated and not RFC4648 compliant

### ISSUE THREAD

**Issue by cthulhuology** [aws-greengrass/aws-greengrass-nucleus#864]
When one subscribes to a topic using the SubscribeToTopic  and sends the binary message 'hello world' as base64 encoded binary message as:

{ "topic": "test/topic", "publishMessage": "binaryMessage" : { "message" : "aGVsbG8gd29ybGQ=" }}}

The subscriber receives the message:

{ "binaryMessage": {"message":""aGVsbG8gd29ybGQ\u003d"}}

And while this is a valid UTF-8 string, it is not a RFC4648 compliant encoding.   This then requires the subscriber to decode the UTF-8 string to get a valid base64 encoded string to then decode.  This is a very non-obvious behavior.  As the '=' character is already a regular UTF-8 code point well supported by 7 bit channels for decades, this double encoding is detrimental.

It should also be noted that this also demonstrates that the message is getting deserialized during processing (producing unnecessary processing overhead), and then being mutated by the IPC system.  This violates most users expectations of how a IPC transit should function as the blob should be treated as an opaque value.

Additionally, the base64 encoding already produces a 33% overhead, and this double encoding only add more unnecessary overhead to each binaryMessage.

**Comment by MikeDombo** [comment]
Hi,
Can you please open this issue in the [SDK repository](https://github.com/aws/aws-iot-device-sdk-java-v2/)?

Thank you.
