### ISSUE TITLE
SubscribeToComponentUpdate should accept component names as an argument

### ISSUE THREAD

**Issue by cthulhuology** [aws-greengrass/aws-greengrass-nucleus#888]
While the current implementation allows the component to listen for update messages for itself, and can defer or update status for itself, this makes it difficult to coordinate updating components when there are dependencies or communication pathways between them and the external system.  It would be better to have the ability to create supervisor components, which manage the orchestration between components (similar to gen_supervisor in the OTP platform (https://erlang.org/doc/man/supervisor.html) which allows a 3rd party component to embody the logic required to handle those dependencies and requirements.

For example, suppose I have a set of sensors which are each being read by individual components that run calibration curves on the per sensor data.  Each of these curves is uniquely calibrated to the specific sensor, and may be updated independently with new configuration values.  These components publish their normalized data to topics which are then consumed by multiple consumers which manage specific tasks (ML inference, servo control, etc),  As coordination between components is vital to the safe operation of the device, we would like to have a supervisor module which can monitor each of the update states, and be able to negotiate the proper sequence of component updates during a deployment.   The supervisor also needs to be update-able too, and be able to hand over it's observation functions to another instance of itself without necessarily requiring restarting any of the components it observes.

By adding this feature it would be possible to implement that supervisor pattern, and enable a supervisor to supervise a supervisor in a supervisor tree.

**Comment by fahadmohammed01** [comment]
Hi Dave,
When a component subscribes to an update using SubscribeToComponentUpdate, nucleus will send an update notification to the component for every deployment. If the component defers the update using DeferComponentUpdate, the deployment as a whole is postponed. This allows a component to postpone the whole deployment (not just the update to itself) allowing it to act as a supervisor.
