### ISSUE TITLE
createUser and  createGroup do not support Busybox

### ISSUE THREAD

**Issue by cthulhuology** [aws-greengrass/aws-greengrass-nucleus#911]
The createUser function uses a nonportable useradd to create the user which is not available in busybox by default:

runCmd("useradd -r -m " + user, o -> {

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/87d89a61342f20e2e84f505af38bd89f68514c2f/src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java#L355

Busyboxy supports a adduser command the equivalent of which would be "adduser -S " + user (the -S is for system).

Similarly, the createGroup function uses 

 runCmd("groupadd -r " + group, o -> {

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/87d89a61342f20e2e84f505af38bd89f68514c2f/src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java#L361

the equivalent Busybox command is

"addgroup -S " + group

It should be noted that on Debian based systems the adduser and addgroup commands are deemed more "user friendly"  though they both use --system instead of -S for their runtime flags.

**Comment by shaguptashaikh** [comment]
Hi Dave, thank you for reporting this, we are looking into it and will provide an update here once fixed
