### ISSUE TITLE
addUserToGroup does not support Busybox 

### ISSUE THREAD

**Issue by cthulhuology** [aws-greengrass/aws-greengrass-nucleus#912]
The function addUserToGroup uses usermod under the hood to add a user to a group

 runCmd("usermod -a -G " + group + " " + user, o -> {

https://github.com/aws-greengrass/aws-greengrass-nucleus/blob/87d89a61342f20e2e84f505af38bd89f68514c2f/src/main/java/com/aws/greengrass/util/platforms/unix/UnixPlatform.java#L367

Busybox based Linux use the command equivalent 

"addgroup " + user + " " + group

https://busybox.net/downloads/BusyBox.html

This option also works on Debian based systems if both the user and the group are pre-existing cf. man 8 adduser

**Comment by shaguptashaikh** [comment]
Hi Dave, thank you for reporting this, we are looking into it and will provide an update here once fixed
