### ISSUE TITLE
com.aws.greengrass.easysetup.GreengrassSetup: Invalid region causes NullPointerException

### ISSUE THREAD

**Issue by eercanayar** [aws-greengrass/aws-greengrass-nucleus#925]
**Describe the bug**
Running easysetup with invalid `--aws-region` causes NullPointerException.

I'm not a Java expert, I just looked at. I see that some controls around `awsRegion` are already implemented on  #883 but I faced this issue on v2.0.5. I'm not sure that why this isn't covered by these controls.

**To Reproduce**
- Follow instructions on the [Quick installation](https://docs.aws.amazon.com/greengrass/v2/developerguide/quick-installation.html)

**Expected behavior**
To return meaningful error message instead of NullPointerException.

**Actual behavior**

```
$ sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE \
>   -jar ./GreengrassCore/lib/Greengrass.jar \
>   --aws-region region \
>   --thing-name MyGreengrassCore \
>   --thing-group-name MyGreengrassCoreGroup \
>   --tes-role-name MyGreengrassV2TokenExchangeRole \
>   --tes-role-alias-name MyGreengrassCoreTokenExchangeRoleAlias \
>   --component-default-user ggc_user:ggc_group \
>   --provision true \
>   --setup-system-service true
Added ggc_user to ggc_group 
Error while trying to setup Greengrass Nucleus
java.lang.NullPointerException
	at com.aws.greengrass.util.RegionUtils.getGlobalRegion(RegionUtils.java:86)
	at com.aws.greengrass.util.IamSdkClientFactory.getIamClient(IamSdkClientFactory.java:47)
	at com.aws.greengrass.easysetup.DeviceProvisioningHelper.<init>(DeviceProvisioningHelper.java:155)
	at com.aws.greengrass.easysetup.GreengrassSetup.performSetup(GreengrassSetup.java:291)
	at com.aws.greengrass.easysetup.GreengrassSetup.main(GreengrassSetup.java:242)

```

Replacing `--aws-region region` with `--aws-region us-east-1` allows to jump from the NPE.

**Environment**
 - OS: Raspbian GNU/Linux 10 (buster)
 - JDK version: 1.8.0_212
 - Nucleus version: 2.0.5

**Comment by MikeDombo** [comment]
Hi,
As you point out this has already been fixed; we just haven't included it in a release yet. It will be included in our upcoming release.
