### ISSUE TITLE
Greengrass stop working after a while

### ISSUE THREAD

**Issue by andrea-pustina** [aws-greengrass/aws-greengrass-nucleus#962]
**Describe the bug**
After some hours all components results as running, but they don't work. They don't publish/receive messages and don't print any log. 
In greengrass.log continously print:
2021-05-05T08:23:35.688Z [INFO] (Thread-4) com.aws.greengrass.mqttclient.AwsIotMqttClient: Connection resumed. {clientId=84fd277845a3, sessionPresent=true}
2021-05-05T08:23:35.745Z [INFO] (pool-2-thread-36) com.aws.greengrass.deployment.ShadowDeploymentListener: Published to get named shadow topic. {}
2021-05-05T08:23:35.755Z [WARN] (Thread-4) com.aws.greengrass.mqttclient.AwsIotMqttClient: Connection interrupted. {clientId=84fd277845a3, error=The connection was closed unexpectedly.}
2021-05-05T08:23:36.191Z [INFO] (Thread-4) com.aws.greengrass.mqttclient.AwsIotMqttClient: Connection resumed. {clientId=84fd277845a3, sessionPresent=true}
2021-05-05T08:23:36.220Z [INFO] (pool-2-thread-36) com.aws.greengrass.deployment.ShadowDeploymentListener: Published to get named shadow topic. {} 
...

**To Reproduce**
This is our configuration.
Component recipe:
```json
{
        "RecipeFormatVersion": "2020-01-25",
        "ComponentName": "component_name",
        "ComponentVersion": "0.0.1",
        "ComponentDescription": "a component",
        "ComponentPublisher": "me",
        "ComponentConfiguration": {
            "DefaultConfiguration": {
                "containerParams": {
                    "memorySize": 16384,
                    "mountROSysfs": False,
                    "volumes": {},
                    "devices": {}
                },
                "containerMode": "NoContainer",
                "timeoutInSeconds": 3,
                "maxInstancesCount": 100,
                "inputPayloadEncodingType": "json",
                "maxQueueSize": 1000,
                "pinned": True,
                "maxIdleTimeInSeconds": 60,
                "statusTimeoutInSeconds": 60,
                "pubsubTopics": {}
            }
        },
        "Manifests": [
            {
                "Name": "Linux",
                "Platform": {
                    "os": "linux"
                },
                "Lifecycle": {
                    "Bootstrap": f"echo 'bootstrap' > /log/{component_name}.status",
                    "Install": f"echo 'install' > /log/{component_name}.status",
                    "Run": f"python3 {{artifacts:decompressedPath}}/component/main.py",
                    "Shutdown": f"echo 'shutdown' > /log/{component_name}.status",
                    "Recover": f"echo 'recover' > /log/{component_name}.status",
                },
                "Artifacts": [
                    {
                        "Uri": f"s3://{bucket_name}/component.zip",
                        "Unarchive": "ZIP",
                    }
                ]
            }
        ]
    }
```
Policy attached to certificate:
```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:Connect"
      ],
      "Resource": "*"
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Receive",
        "iot:Publish"
      ],
      "Resource": [
        "arn:aws:iot:eu-west-1:account_id:topic/$aws/things/84fd277845a3*/greengrassv2/health/json",
        "arn:aws:iot:eu-west-1:account_id:topic/$aws/things/84fd277845a3*/jobs/*",
        "arn:aws:iot:eu-west-1:account_id:topic/$aws/things/84fd277845a3*/shadow/*",
        "arn:aws:iot:eu-west-1:account_id:topic/84fd277845a3/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "iot:Subscribe"
      ],
      "Resource": [
        "arn:aws:iot:eu-west-1:account_id:topicfilter/$aws/things/84fd277845a3*/jobs/*",
        "arn:aws:iot:eu-west-1:account_id:topicfilter/$aws/things/84fd277845a3*/shadow/*",
        "arn:aws:iot:eu-west-1:account_id:topicfilter/84fd277845a3/*"
      ]
    },
    {
      "Effect": "Allow",
      "Action": [
        "greengrass:GetComponentVersionArtifact",
        "greengrass:ResolveComponentCandidates"
      ],
      "Resource": "*"
    }
  ]
}
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:AssumeRoleWithCertificate",
      "Resource": "arn:aws:iot:eu-west-1:account_id:rolealias/GreengrassCoreTokenExchangeRoleAlias"
    }
  ]
}
```
GreengrassCoreTokenExchangeRoleAlias Policy 
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "iot:DescribeCertificate",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "logs:DescribeLogStreams",
                "iot:Connect",
                "iot:Publish",
                "iot:Subscribe",
                "iot:Receive",
                "s3:GetBucketLocation",
                
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetObjectVersion",
            ],
            "Resource": f"arn:aws:s3:::greengrass-components-artifacts-{region}/*"
        }
    ]
}
```

**Expected behavior**
Components continue to work

**Actual behavior**
Component stop working after a while

**Environment**
 - OS: Raspbian
 - JDK version: 1.8
 - Nucleus version: 2.0.5

**Additional context**
with "systemctl restart greengrass.service" everything works correctly again

**Comment by andrea-pustina** [comment]
Thanks Kris.

we are testing with a deployment with only one "heartbeat" component that sends a message '{"top": "heartbeat", "time":4617387237}' on the topic "ABF8CCDD44/heartbeat" every 30 seconds. I don't think that we are exceeding any of the MQTT message restrictions

**Comment by MikeDombo** [comment]
IoT Core will disconnect any device with a duplicated client ID, please make sure that you aren't running 2 copies of Greengrass which would be conflicting.

I would recommend upgrading to version 2.1.0 of the Nucleus as several MQTT issues have been addressed.

I'd also recommend configuring IoT Core debug logging which should enable you to see the reason why Greengrass is getting disconnected. https://docs.aws.amazon.com/iot/latest/developerguide/configure-logging.html

**Comment by mora0136** [comment]
I believe I know the solution to your problem.

I strongly suggest enabling the logs like Mike suggested and observe the reason for disconnect.

I encountered a similar issue and what fixed it for me was to update the security policy on the certificate so that it is able to publish to /greengrassv2/health/json and /greengrass/health/json. I am unsure why greengrassv2 still uses legacy greengrass mqtt topic but it does, and the minimal security policy provided by AWS docs doesn't reflect this.

Hope this helps.

**Comment by andrea-pustina** [comment]
Thanks Mike and mora

we had enabled log this morning and we update to 2.1.0

tomorrow morning we will see if there is the issue yet and in case we will try the mora's solution.

We will keep you informed.

**Comment by andrea-pustina** [comment]
Our issue seems different from the mora's one.

This morning we found this error in the log that continuously repeats:
{"thread":"pool-2-thread-25","level":"INFO","eventType":null,"message":"Connecting to AWS IoT Core","contexts":{"clientId":"14b457da94dc"},"loggerName":"com.aws.greengrass.mqttclient.AwsIotMqttClient","timestamp":1620875054777,"cause":null}
{"thread":"Thread-4","level":"ERROR","eventType":null,"message":"Unable to connect to AWS IoT Core","contexts":{"clientId":"14b457da94dc"},"loggerName":"com.aws.greengrass.mqttclient.AwsIotMqttClient","timestamp":1620875055454,"cause":{"message":"A query to dns failed to resolve.","suppressed":[],"stackTrace":[{"methodName":"onConnectionComplete","fileName":"MqttClientConnection.java","lineNumber":133,"className":"software.amazon.awssdk.crt.mqtt.MqttClientConnection","nativeMethod":false}],"cause":null}}
{"thread":"pool-2-thread-25","level":"ERROR","eventType":null,"message":"Error when publishing from spooler","contexts":{},"loggerName":"com.aws.greengrass.mqttclient.MqttClient","timestamp":1620875055457,"cause":{"message":"software.amazon.awssdk.crt.mqtt.MqttException: A query to dns failed to resolve.","suppressed":[],"stackTrace":[{"methodName":"reportGet","fileName":"CompletableFuture.java","lineNumber":357,"className":"java.util.concurrent.CompletableFuture","nativeMethod":false},{"methodName":"get","fileName":"CompletableFuture.java","lineNumber":1895,"className":"java.util.concurrent.CompletableFuture","nativeMethod":false},{"methodName":"runSpooler","fileName":"MqttClient.java","lineNumber":642,"className":"com.aws.greengrass.mqttclient.MqttClient","nativeMethod":false},{"methodName":"call","fileName":"Executors.java","lineNumber":511,"className":"java.util.concurrent.Executors$RunnableAdapter","nativeMethod":false},{"methodName":"run","fileName":"FutureTask.java","lineNumber":266,"className":"java.util.concurrent.FutureTask","nativeMethod":false},{"methodName":"runWorker","fileName":"ThreadPoolExecutor.java","lineNumber":1149,"className":"java.util.concurrent.ThreadPoolExecutor","nativeMethod":false},{"methodName":"run","fileName":"ThreadPoolExecutor.java","lineNumber":624,"className":"java.util.concurrent.ThreadPoolExecutor$Worker","nativeMethod":false},{"methodName":"run","fileName":"Thread.java","lineNumber":748,"className":"java.lang.Thread","nativeMethod":false}],"cause":{"message":"A query to dns failed to resolve.","suppressed":[],"stackTrace":[{"methodName":"onConnectionComplete","fileName":"MqttClientConnection.java","lineNumber":133,"className":"software.amazon.awssdk.crt.mqtt.MqttClientConnection","nativeMethod":false}],"cause":null}}}


The problem seems to be DNS, but we have an external service to greengrass (on the same raspberry) that continues to work all the night. 
In case that DNS went down for a short period (i think that is not probable), we expected that greengrass restarts working and we don't understand why it goes in this error state.

We know that if we restart greengrass it works, but we would like to find a different solution

Any ideas?

**Comment by MikeDombo** [comment]
Greengrass will absolutely retry and it should eventually be able to send. I'll create an issue with the SDK to get some help understanding what could cause this problem.

**Comment by andrea-pustina** [comment]
Thank you Mike.

We are doing some test on three different devices and at the same time they started to repeatedly write this into log:
{"thread":"Thread-6","level":"INFO","eventType":null,"message":"Connection resumed","contexts":{"clientId":"14b457da94dc","sessionPresent":"true"},"loggerName":"com.aws.greengrass.mqttclient.AwsIotMqttClient","timestamp":1620996307089,"cause":null}
{"thread":"pool-2-thread-65","level":"INFO","eventType":null,"message":"Published to get named shadow topic","contexts":{},"loggerName":"com.aws.greengrass.deployment.ShadowDeploymentListener","timestamp":1620996307091,"cause":null}
{"thread":"pool-2-thread-64","level":"DEBUG","eventType":null,"message":"Requesting the next deployment","contexts":{"ThingName":"14b457da94dc"},"loggerName":"com.aws.greengrass.deployment.IotJobsHelper","timestamp":1620996307091,"cause":null}
{"thread":"pool-2-thread-65","level":"DEBUG","eventType":null,"message":"Updating status of persisted deployments to subscribers","contexts":{"deploymentType":"SHADOW","numberOfSubscribers":"2"},"loggerName":"com.aws.greengrass.deployment.DeploymentStatusKeeper","timestamp":1620996307091,"cause":null}
{"thread":"pool-2-thread-64","level":"DEBUG","eventType":null,"message":"Updating status of persisted deployments to subscribers","contexts":{"deploymentType":"IOT_JOBS","numberOfSubscribers":"2"},"loggerName":"com.aws.greengrass.deployment.DeploymentStatusKeeper","timestamp":1620996307092,"cause":null}
{"thread":"Thread-6","level":"WARN","eventType":null,"message":"Connection interrupted","contexts":{"clientId":"14b457da94dc","error":"The connection was closed unexpectedly."},"loggerName":"com.aws.greengrass.mqttclient.AwsIotMqttClient","timestamp":1620996307188,"cause":null}


I think that this is the first problem for which we write this github issue. Maybe the DNS issue is another problem.

We were not doing deployments when the error appears.

I see that in the deployment there is: "numberOfSubscribers:2", but I don't know if it is normal.
ad-6","level":"WARN","eventType":null,"message":"Connection interrupted","contexts":{"clientId":"14b457da94dc","error":"The connection was closed unexpectedly."},"loggerName":"com.aws.greengrass.mqttclient.AwsIotMqttClient","timestamp":1620996307188,"cause":null}

From the dashboard in device activity we continously see connections and disconnections like this:
{
  "clientId": "84fd277845a3",
  "timestamp": 1620897349525,
  "eventType": "disconnected",
  "clientInitiatedDisconnect": false,
  "sessionIdentifier": "6b671266-1e50-4519-bfa6-4c85562b0822",
  "principalIdentifier": "f9a2125ad73ce919abb5ddfb98bdc7fe8e8522fa6b0dea84336596dc6d345092",
  "disconnectReason": "CLIENT_ERROR",
  "versionNumber": 1189389
}

The three devices have different id/arn/thing_name.

I think that this is the first problem for which we write this github issue. Maybe the DNS issue is another problem.

We were not doing deployments when the error appears.

I see that in the deployment there is: "numberOfSubscribers:2", but I don't know if it is normal.

**Comment by MikeDombo** [comment]
Have you enabled DEBUG level IoT logs in the console? It should tell you more than just CLIENT_ERROR; it should tell us exactly what the issue is which causes the disconnect.

**Comment by andrea-pustina** [comment]
We have enabled DEBUG log yet

**Comment by MikeDombo** [comment]
If there are no additional more clear errors in the IoT debug logs, then I would suggest to open a support ticket in the AWS Console with IoT so that they can identify the exact reason for the disconnection.

**Comment by andrea-pustina** [comment]
Probably we find out that the problem is the one suggested by Mora (thanks again!)

In the greengrass log on the device the error is incomprehensible, but we found out this in cloudwatch:
2021-05-17 07:34:01.116 TRACEID:49123687-e906-7af0-d4b9-60ee36cb635b PRINCIPALID:f9a2125ad73ce919abb5ddfb98bdc7fe8e8522fa6b0dea84336596dc6d345092 [ERROR]  EVENT:PublishEvent TOPICNAME:$aws/things/84fd277845a3/greengrass/health/json MESSAGE:PublishIn Status: AUTHORIZATION_ERROR Failure reason:AUTHORIZATION_FAILURE

We suggest to correct this issue in the next release or to update the documentation.

We are doing some test and we will let know if the problem solved

**Comment by MikeDombo** [comment]
Thank you for finding that, I'll inform our docs team and have that fixed ASAP.
