### ISSUE TITLE
(EasySetup): provide an option to store certificates in a separate folder from Greengrass Root

### ISSUE THREAD

**Issue by massi-ang** [aws-greengrass/aws-greengrass-nucleus#971]
**Feature Description**
Greengrass Easy Setup should provide an option to store certificates and the initial config.yaml in a separate folder from Greengrass Root. This will simplify the setup of the system by separating RO data from RW data and enable a simple factory reset of the device.

**Use Case**
In order to setup my device in way that allows for en easy factory reset I currently need to first install Greengrass with the following procedure

1. install greengrass using the Console provided command but with `--deploy-dev-tools false --start false`
2. Copy `/greengrass/v2/config/effectiveConfig.yaml` in a separate folder
3. Copy the certificates and private key in a separate folder
4. Edit `effectiveConfig.yaml` and replace the location of the certificates and private key with the paths to where you copied them

After this is done I can easily reset the device by removing the Greengrass root folder and then launch Greengrass with:

```bash
sudo -E java -Droot="/greengrass/v2" -Dlog.store=FILE -jar ./GreengrassCore/lib/Greengrass.jar --provision false --setup-system-service true --config <path to effectiveConfig.yaml
```

**Proposed Solution**

Add a flag to Easy Setup to specify a separate folder from the Greengrass root folder where to store the certificates and the initial config.yaml. 
If this flag is provided, Greengrass stores there the device certificates, RootCA and the initial effectiveConfig.yaml. 
The configuration refers to the certificates stored in this separate folder, and no certificates are stored in the greengrass root folder.

**Other**
Add detailed explanation, stacktraces, related issues, links for us to have context, etc

* [X] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

**Comment by MikeDombo** [comment]
Hi Massi, 
This is already supported using the `--init-config` option. The certificates and so on can be in any directory at all, you just need to provide the path to Greengrass in the config file passed in the `--init-config` option.

**Comment by massi-ang** [comment]
Hi Mike,
thanks for the clarification, but what I meant in term of feature is slightly different. When using EasyConfig with the `--provision` flag, Greengrass creates device certificates and configuration files for you, but it will always store them in the Greengrass root directory. I would like to have a command line option to specify an alternative directory where Greengrass could put the certificates and the config file and the config file and the config file already configured with the correct paths to the certificates.

Currently I need to first run Greengrass with`--provision` flag, and then move the certificates and the config file to a new location and manually edit the config file to set the correct paths to the certificates.
